linuxwacom/libwacom

- data/huion-h610-pro.tablet
Edited the Huion H610's file to add support for the Turcom TS-6610 tablet.
> Added support for the Turcom TS-6610

- data/elan-24db.tablet
Ref: https://github.com/linuxwacom/libwacom/issues/30
Signed-off-by: Jason Gerecke <killertofu@gmail.com>
> data: Add Elan 24db (HP Spectre x360 Convertible 13-ac0XX)

- data/isdv4-486a.tablet
Ref: https://github.com/linuxwacom/libwacom/issues/35
> data: Add ISDv4 486a (Dell XPS 15 9575)

- data/isdv4-516b.tablet
Ref: https://github.com/linuxwacom/libwacom/issues/34
> data: Add ISDv4 516B (Lenovo Yoga 730-15IKB)

- data/isdv4-5150.tablet
Ref: https://github.com/linuxwacom/libwacom/issues/36
> data: Add ISDv4 5150 (Lenovo ThinkPad X380 Yoga)

- data/isdv4-5122.tablet
Ref: https://github.com/linuxwacom/wacom-hid-descriptors/issues/40
> data: Add support for ISDv4 5122 (Lenovo 300e 81FY)

- data/isdv4-4865.tablet
Ref: https://github.com/linuxwacom/wacom-hid-descriptors/issues/43
Signed-off-by: Jason Gerecke
> data: Add ISDv4 4865 (HP EliteBook x360 1020 G2)

- data/isdv4-4870.tablet
Ref: https://github.com/linuxwacom/wacom-hid-descriptors/issues/42
> data: Add support for ISDv4 4870 (HP Elite x2 1013 G3)

- data/bamboo-0fg-s-p-alt.tablet
Ref: https://github.com/linuxwacom/libwacom/issues/54
Signed-off-by: Jose Luis Tirado <joseluis.tirado@gmail.com>
> data: Add Bamboo Fun 4x5 (CTE-450)

- data/bamboo-one-m-p.tablet
> Adding tablet file for CTE-660

- data/elan-5515.tablet
> Support for Acer Switch SA5-271P

- data/bamboo-0fg-m-p-alt.tablet
- data/layouts/bamboo-0fg-s-p-alt.svg
Also introduces an appropriate layout file and updates the CTE-450 to use it.
> data: Add Bamboo Fun 5x9 (CTE-650)

- data/isdv4-4841.tablet
- data/isdv4-5157.tablet
- data/isdv4-5158.tablet
- data/isdv4-517d.tablet
Add a trio of new ISDv4 devices from wacom-hid-descriptors and update a device name.
> New devices

- data/isdv4-5169.tablet
Ref: https://github.com/linuxwacom/wacom-hid-descriptors/issues/52
> Add ISDv4 5169 (Lenovo YOGA 730-15IWL)

- data/isdv4-5128.tablet
Ref: https://github.com/linuxwacom/xf86-input-wacom/issues/53
> data: Add ISDv4 5128 (Lenovo YOGA 720-12IKB)

- data/dtk-1660e.tablet
> data: add DTK-1660E .tablet file

- data/isdv4-50e9.tablet
Ref: https://github.com/linuxwacom/wacom-hid-descriptors/issues/57
> data: Add ISDv4 50E9 (Lenovo ideapad FLEX 5-1570)

- data/bamboo-2fg-fun-m-pt.tablet
- data/bamboo-2fg-fun-s-pt.tablet
- data/bamboo-2fg-s-pt.tablet
- data/bamboo-2fg-s-t.tablet
- data/graphire-wireless-8x6.tablet
6 year old patch that never made it upstream. But someone's gone through the effort of painting these pretty pictures, so we might as well push it.
> data: add button positions for some older graphire and bamboos

- data/isdv4-513b.tablet
Ref: https://github.com/linuxwacom/wacom-hid-descriptors/issues/59
> data: Add ISDv4 513B (Lenovo MIIX 520-12IKB)

- data/isdv4-4806.tablet
Ref: https://github.com/linuxwacom/wacom-hid-descriptors/issues/58
> data: Add ISDv4 4806 (Dell Latitude 5175)

- data/wacom.example
Replace Sourceforge url with equivalent Github url.
> data: keep url in wacom.example current

- .travis.yml
This started out as something more complicated but for now just this set will do and already helps a bit.
Conflicts with #124 but if we're happy with this we can just close the other one - it includes the changes here.
> travis CI: simplify the travis script a bit

- test/test-stylus-validity.c
See https://github.com/linuxwacom/libwacom/pull/122#discussion_r304541074 and https://github.com/linuxwacom/libwacom/pull/122#discussion_r304542747
> test: test for the various stylus features explicitly

- data/cintiq-22.tablet
- meson.build
> data: add support for Cintiq 22

- meson.build
- meson_options.txt
> A bunch of meson cleanups

- data/isdv4-2d1f-002e.tablet
- meson.build
Ref: https://github.com/linuxwacom/wacom-hid-descriptors/issues/60
Ref: https://github.com/linuxwacom/libwacom/issues/139
> data: Add ISDv4 2E (Samsung 930QAA)

- .travis.yml
- Makefile.am
- run-full-test.sh
And add the required bits to the test systems so this can't happen again.
> Add meson_options.txt to EXTRA_DIST

- .travis.yml
- configure.ac
- meson.build
- meson_options.txt
- tools/Makefile.am
- tools/generate-udev-rules.c
> Install the udev rules

- .travis.yml
- Makefile.am
Picks up missing EXTRA_DIST entries and similar.
> travis ci: build with autotools from a tarball too

- data/isdv4-5115.tablet
- data/libwacom.stylus
- meson.build
- test/test-stylus-validity.c
Added descriptions for the tablet and the common Thinkpad Pro Pen
> Add Wacom HID 5115 support

- meson.build
Fixes https://github.com/linuxwacom/libwacom/issues/162
> meson: add private requires to .pc

- data/isdv4-48c9.tablet
- meson.build
Ref: https://github.com/linuxwacom/wacom-hid-descriptors/issues/62
> data: Add ISDv4 48c9 (Dell Latitude 7400 2-in-1)

- data/isdv4-48ed.tablet
- meson.build
Ref: https://github.com/linuxwacom/wacom-hid-descriptors/issues/65
> data: Add ISDv4 48ED (Dell XPS 13 2-in-1 7390)

- data/isdv4-51bf.tablet
- meson.build
Ref: https://github.com/linuxwacom/wacom-hid-descriptors/issues/61
> data: Add ISDv4 51BF (Lenovo X1 Yoga 4th)

- data/isdv4-5147.tablet
- meson.build
Ref: https://github.com/linuxwacom/wacom-hid-descriptors/issues/66
> data: Add ISDv4 5147 (Lenovo ThinkPad X1 Yoga 3rd)

- data/isdv4-5196.tablet
- meson.build
Ref: https://github.com/linuxwacom/wacom-hid-descriptors/issues/69
> data: Add ISDv4 5196 (Lenovo YOGA C930-13IKB)

- data/isdv4-51c4.tablet
- meson.build
Ref: https://github.com/linuxwacom/wacom-hid-descriptors/issues/74
> data: Add ISDv4 51C4 (Lenovo IdeaPad FLEX-14API)

- data/isdv4-4875.tablet
- meson.build
Ref: https://github.com/linuxwacom/wacom-hid-descriptors/issues/77
> data: Add ISDv4 4875 (Dell XPS 15 9575)

- data/isdv4-149.tablet
- meson.build
Ref: https://github.com/linuxwacom/libwacom/issues/183
> data: Add ISDv4 149 (Toshiba z20t-c)

- data/isdv4-51b8.tablet
- meson.build
Ref: https://github.com/linuxwacom/wacom-hid-descriptors/issues/76
> data: Add ISDv4 51B8 (Lenovo ThinkPad X1 Yoga 4th)

- data/isdv4-51a0.tablet
- meson.build
Ref: https://github.com/linuxwacom/wacom-hid-descriptors/issues/80
> data: Add ISDv4 51A0 (Lenovo ThinkPad X1 Extreme 2nd)

- .github/ISSUE_TEMPLATE/New_device_support.md
As suggested by @ohthehugemanatee in https://github.com/linuxwacom/libwacom/pull/207#issuecomment-583480334
> github templates: note that a meson.build entry is needed for new files

- data/elan-0732.tablet
Seems to work on my envy x360, I just copied elan-262b.tablet and changed the device match.
Is there anything else I need to check?
> data: Add elan-0732 (HP ENVY x360 Convertible 13-ag0xxx)

- .travis.yml
- meson.build
Fixes a warning from Meson when configuring the project, and corrects build issues that have just popped up with Travis
> Build system fixes

- data/libwacom.stylus
A pair of updates to the comments about two specific HP AES pens.
> Active pen g3

- data/cintiq-16-2.tablet
- data/dtk-1660e-2.tablet
DTK-1660E
Signed-off-by: Ping Cheng <ping.cheng@wacom.com>
> Add data files for the second generation of Cintiq 16 and

- data/elan-2514-alt.tablet
https://github.com/linuxwacom/libwacom/issues/275
I wasn't sure what to name the file. Let me know if I should change something.
> Add HP Pavilion x360 Convertible 14-dh0xxx

- data/wacom.example
Let's try to make this the goto file that explains everything that we can
easily link to.
> data: update the example file with more instructions

- data/intuos-s-p3-wl.tablet
See commit cf14268c164022887f6d35eea4ef5b540d94702a for the non-wireless
version.
> data: fix EvdevCodes for CTL-4100WL

- data/surface-go.tablet
Link: https://github.com/linuxwacom/wacom-hid-descriptors/issues/51
> data: Add support for the Microsoft Surface Go

- data/hp-pro-tablet-408.tablet
Link: https://github.com/linuxwacom/wacom-hid-descriptors/issues/137
> data: Update HP Pro Tablet 408 tablet file

- libwacom/libwacom.c
- meson.build
- test/test-dbverify.c
- tools/libwacom-list-local-devices.man
- tools/list-local-devices.c
And misc other fixes to the list-local-devices tool
Fixes #372
> List each device only once in libwacom-list-local-devices

- test/test-load.c
Just cleaning out old branches here, this is a commit from... quite a while ago
> test: add a load test for the dell canvas

- libwacom/libwacom-database.c
Fixes #378 but replaces that whole line immediately after with a more useful error message.
> Fix a null printf, followed by a replacement of that error message

- libwacom/libwacom-database.c
- libwacom/libwacom.c
- libwacom/libwacomint.h
- libwacom/util-strings.h
We have glib anyway, make use of it
> Drop use of streq/strneq, use glib's versions instead

- data/elan-2514-alt2.tablet
Content extracted from #335 and merged into the existing tablet file.
Closes #335
cc @ConfusedOwlet
> data: add support for ELAN-2514 variant 04f3:25bf

- data/elan-2514.tablet
> data: add support for ELAN-2514 variant 04f3:2718

- data/isdv4-2d1f-524c.tablet
Link: https://github.com/linuxwacom/wacom-hid-descriptors/issues/157
> data: Add Lenovo ThinkVision M14t

- .github/workflows/pages.yml
Sits on top of #413 
Fixes #102
> CI: add a github pages job for our doxygen output 

- data/elan-24d8.tablet
Added elan-24d8.tablet info from HP ProBook 435 G7
> data: Add elan-24d8 (HP ProBook 435 G7)

- data/xp-pen-star03.tablet
This should fix #420. 
The changes are done according to the issue.
> data: update device match (#420)

- README.md
- meson_options.txt
No need for everyone to build this, it's on github pages now
> Disable building the documentation by default

- data/wacom.example
One 'f' too many
Exposed in #441
> data: fix the example sylus comment

- data/elan-2bb3.tablet
- data/elan-9008.tablet
Link to [wacom-hid-descriptors/issues/179](https://github.com/linuxwacom/wacom-hid-descriptors/issues/179)
Thank you!
> add ELAN 2BB3 (Asus Zenbook Flip S13 UX371)

- .github/workflows/check-for-sysinfo.yml
> Check for sysinfo data to be in data files

- data/elan-2a70.tablet
Hi,
I have now tried to create a pull request for my changes for the elan-2a70 at my HP ProBook X360 11 G5 EE.
I hope this worked. ;)
The related libwacom issue: https://github.com/linuxwacom/libwacom/issues/465 
And this was the related wacom-hid-descriptors issue: https://github.com/linuxwacom/wacom-hid-descriptors/issues/185
Thanks
Mark
> Add description for elan-2a70

- README.md
- data/huion-h1060p.tablet
- data/layouts/huion-h1060p.svg
This is a cleaned-up version of #499
> Add support for the Huion H1060P

- data/isdv4-49c8.tablet
This commit adds support for Dell Inspiron 14 7425 2-in-1.
> Add tablet for Dell Inspiron 14 7425 2-in-1

- tools/clean_svg.py
> tools/clean_svg: don't modify the dict while iterating

- data/xp-pen-star03.tablet
[sysinfo.c0SY4Un4cx.tar.gz](https://github.com/linuxwacom/libwacom/files/10113210/sysinfo.c0SY4Un4cx.tar.gz)
> Add Ugee M708 v1 tablet

- data/elan-2514.tablet
HP Spectre x360 Convertible 14-ea0xxx
https://github.com/linuxwacom/wacom-hid-descriptors/issues/177
> Add support for HP Spectre x360 14

- data/isdv4-52d5.tablet
I'm not sure about the height and width, as I don't know the units the file wants, but I'll happily fill this in if you have any pointers. It's 302x188mm according to `libinput`.
Let me know if anything else is missing :)
> Add Wacom HID 52D5 (Lenovo Yoga 7 14ARB7)

- data/elan-2c1b.tablet
- data/elan-2d55.tablet
data files taken from #566
Fixes #566
cc @mtlg - happy for me to merge these? They're your work, so feel free to create a PR for the proper attribution in the git commits, otherwise I'll just merge them as found in that zip file.
Can you double check the comments please, though, you didn't update them in the files so I had to take a guess
> data: add ELAN 2C1B and 2D55 (Asus ZenBook Pro Duo UX482EG)

- data/huion-h950p.tablet
Fixes #574
cc @ledbettj does this fix the issue? I might have a copy/paste here, please double-check
> data: include another device name for the Huion H950P

- data/wacom-one-12.tablet
- data/wacom-one-13.tablet
Adding tablet files for two new Wacom products.
> data: add Wacom One 12 & Wacom One 13

- data/elan-22f7.tablet
Link: https://github.com/linuxwacom/wacom-hid-descriptors/issues/48
> data: Add support for Nuvision Solo 10 Draw

- data/dtc-121.tablet
- data/dth-134.tablet
Adding tablet files for a new Wacom product.
Signed-off-by: Joshua Dickens <joshua.dickens@wacom.com>
> data: add dtc121

- data/xp-pen-g430s.tablet
Ref: https://www.xp-pen.com/download/star-g430s.html
I mostly copied the file for the XP-Pen G430. If any changes are necessary or some physical testing of the device is necessary, please let me know and I will do it as soon as possible!
> Add data for XP-Pen G430s

- data/isdv4-5229.tablet
> Append to DeviceMatch for X1 Yoga Gen 5

- .github/workflows/freebsd.yml
Run it on Ubuntu and update to freebsd-vm@v1
---
Suggested by @jbeich in https://github.com/linuxwacom/libwacom/pull/648#issuecomment-2067557142
> github: fix the BSD workflow

- .github/workflows/main.yml
- .github/workflows/pages.yml
Ubuntu 22.04 is our base distribution so let's use the version that comes with that.
> github: bump python versions to 3.10

- data/huion-inspiroy-2-l---h1061p.tablet
- data/huion-inspiroy-2-m---h951p.tablet
- data/layouts/huion-inspiroy-2-l---h1061p.svg
- data/layouts/huion-inspiroy-2-m---h951p.svg
- data/layouts/huion-inspiroy-2-s---h641p.svg
remove stray commas from the S version and add a dial to the L and M version
> Fix the Inspiroy 2 SVG files

- libwacom/libwacom.c
Both are set by udev based on the sysattr entries anyway and using the properties instead of the sysfs attr means we can override both via udev rules should that become necessary.
cc @JoseExposito
> Fetch the name and uniq from udev properties, not sysfs

- .github/actions/pkginstall/install-pip.sh
- .github/workflows/check-for-sysinfo.yml
- .github/workflows/label-commenter.yml
- .github/workflows/main.yml
- .github/workflows/pages.yml
and bump the CI to use the latest ubuntu and python
> CI: handle python3.12's EXTERNALLY-MANAGED file

- test/test_libwacom.py
> test: fix test suite failure if the database isn't installed

- data/elan-4259.tablet
- data/elan-42ec.tablet
Adding .tablet files for both displays for zenbook duo UX8406MA 1200p-version
> data: add ELAN 9008 and 9009 (zenbook duo UX8406MA 1200p)

- data/layouts/xp-pen-artist24-pro.svg
- data/xp-pen-artist-24-pro.tablet
I don't have the device physically but @deevad provided a sysinfo. It's [physically identical to the 22R Pro](https://www.xp-pen.com/product/artist-24-pro.html) (apart from the size) so most of this is copied from what I did there.
> data: Add support for the XP-Pen Artist 24 Pro

- data/elan-5515.tablet
- data/huion-mini-keydial-kd100.tablet
- data/xp-pen-ack05-remote.tablet
- test/test-tablet-validity.c
Follow-up to commit 081e03af0899 ("Add a new IntegratedIn=Remote flag")
> data: mark our remotes as IntegratedIn=Remote

- data/layouts/xp-pen-innovator-16.svg
- data/xp-pen-innovator-16.tablet
I'm on Ubuntu 24.10 Wayland, am I misunderstanding something here? Weren't there supposed to be options to configure the buttons, dials etc in the options? Thanks
> data: add XP Pen Innovator 16 definition & layout

- test/__init__.py
- test/test_libwacom.py
Fallout from writing tests for #844
> A few cleanups in the tests

- .github/workflows/main.yml
> CI: add a list-local-devices check
