linuxwacom/libwacom

data/graphire4-6x8.tablet
data/layouts/graphire4-6x8.svg

This data was copied from the graphire4 4x5 tablet data file with the obvious changes made wrt USB ID and size.
I am unsure, however, if this is entirely correct. eg the data file says 2 buttons, but the mouse instrument has 3 buttons. Empirically the mouse left button seems to trigger same event as a stylus tap,  right button triggers same event as the bottom stylus button, and middle button triggers same event as top stylus button.  
The 2 buttons on the tablet itself though don't generate any button events under wayland. The wheel scroll on the tablet and mouse also don't generate anything.  So perhaps I'm missing some key data in this file ?

Add entries for graphire4 6x8 tablet

---

libwacom/libwacom.c

The name is freed a few lines down as we fall through to the 'bail:' label.
The only exception is when we actually return the device, that's where we need
to free it manually.
This is just to shut up coverity, this code can only be triggered by supplying
an invalid WacomFallbackFlag.

Don't double-free of the name during matching

---

libwacom/libwacom.c

The nested loop of this comparison function looked malformed, 
as it was always comparing only against the first match by incrementing and comparing to the wrong variable.
So I decided to propose this change.

libwacom.c :: compare_matches: fix nested loop

---

data/isdv4-502a.tablet

Add support for the Toshiba Portege X20W-D Convertible and Toshiba TruPen

data: Add ISDv4 502A (Toshiba Portege X20W-D Convertible and Toshiba TruPen)

---

.github/ISSUE_TEMPLATE/Bug_report.md
.github/ISSUE_TEMPLATE/New_device_support.md

The hope here is that it cuts down on reporters filing issues in libwacom that then need to be moved to input-wacom, xf86-input-wacom or libinput. Or /dev/null ;)
Happy to modify the templates as needed

Add issue templates for github bug reports

---

data/intuos-pro-2-l-wl.tablet
data/intuos-pro-2-l.tablet
data/intuos-pro-2-m-wl.tablet
data/intuos-pro-2-m.tablet

The device itself doesn't use a 2, so let's drop it here
Fixes #64
cc @tb2097

data: drop the '2' from the Intuos Pro 2 names

---

data/cintiq-pro-24-p.tablet
data/cintiq-pro-24-pt.tablet

Fix for [[#68]]; ExpressKeys/Express Keys issue can be skipped due to possible legacy support issues.

Cintiq Pro 24 naming consistency with xsetwacom

---

data/isdv4-515a.tablet

Added support for Wacom ISDv4 515a as found in Lenovo ThinkPad L380 Yoga

data: Add ISDv4 515a (Lenovo ThinkPad L380 Yoga)

---

data/isdv4-5157.tablet

Wacom Tablet as found in my Thinkpad L380 Yoga (20M8S01400)
There is also another .tablet file for L380 (isdv4-515a / 056a:515a), this might be for the 20M7 version.
------------
lsusb:
Bus 001 Device 003: ID 056a:5157 Wacom Co., Ltd 
Device Descriptor:
bLength                18
bDescriptorType         1
bcdUSB               2.00
bDeviceClass            0 (Defined at Interface level)
bDeviceSubClass         0 
bDeviceProtocol         0 
bMaxPacketSize0        64
idVendor           0x056a Wacom Co., Ltd
idProduct          0x5157 
bcdDevice            0.02
iManufacturer           1 Wacom Co.,Ltd.
iProduct                2 Pen and multitouch sensor
iSerial                 0 
bNumConfigurations      1
Configuration Descriptor:
bLength                 9
bDescriptorType         2
wTotalLength …

Add ISDv4 5157 (Lenovo ThinkPad L380 Yoga)

---

test/Makefile.am
test/test-dbverify.c
test/test-load.c
test/test-tablet-validity.c

Add parsing of the `LIBWACOM_DATA_DIR` variable to override our test path. So during normal `make check` we do the same thing as before, but we can also test an installed version of libwacom with the same tests, e.g. `LIBWACOM_DATA_DIR=/usr/share/libwacom make check`. This should make it easier to spot missing files or general path mixups.
Note: first commit is #77

Allow for the tests to be "relocatable"

---

data/elan-2627.tablet

This model is found in the HP Envy x360 ag0xxxx series.
I have a few questions though:
* Width and height, couldn't really find them specified by HP so I just used a ruler and rounded up to the closest amount of inches. Does that make sense or should I round down to 11 and 6 instead?
* The device class is giving me trouble. `PenDisplay` seems the most appropriate but if I use that the Pen doesn't work at all. Switching to Intuos4 makes the pen work but the tracking is bonkers slow, the pointer lags behind the pen a great deal, almost a second and its location is off. I also tried `Class=ISDV4` which seems to get me the same result as `Class=Intuos4`. Which one should I pick?
* Touching the screen (with my finger) seems to result in multiple events. So for example when I touch the header …

Tablet config for ELAN 2627

---

tools/list-local-devices.c

Makes it easier to identify where an entry comes from.
Related #95

tools: print the device node for list-local-devices

---

libwacom/libwacom.c
tools/list-local-devices.c

This is on top of #96 
Some rework in printing devices so we only call `dprintf` once for each line (for some of them anyway) and we can prefix a `#` in front of empty led or button lines.

Some printing cleanups

---

libwacom/libwacom.c

We don't have serial touchpad devices that we care about, but the current code ends up labeling any serial touchpad as supported device with vid/pid 0 - which in turn maps to our serial ISDV4 devices.
Fixes #100 
cc @daenney

Ignore serial touchpads

---

libwacom/libwacom-database.c

Little effect for most users of the database, but the generated udev rules
become more predictable and a lot easier to patch this way.
I wrote this 5 years ago and never pushed it :astonished:

Return the device database sorted by vendor/product ID

---

libwacom/libwacom.h
test/test-load.c

The vendor and product ids are all signed integers except in the
libwacom_match code where they are uint32_t. We can't change that
without API changes (not ABI though), so let's just document it and move on.

Document the signed-ness mismatch between vendor ids

---

.gitignore
configure.ac
libwacom/Makefile.am
libwacom/libwacom-database.c
libwacom/libwacom-error.c
libwacom/libwacom.c
libwacom/libwacom.sym
libwacom/libwacomint.h
test/Makefile.am
test/test-ltversion.c

We've used the libtool versioning scheme in the past which basically requires us to bump the version with every release. And the list of exported function was obtained via a regex.
But libwacom is stable, we don't plan to do backwards-incompatible changes.
Let's handle symbols properly, first by marking all the functions we want to export and second by replacing the lt version/regex with a proper symbol map.

Switch to proper symbol versioning

---

.travis.yml

If something fails, it's better to see the full output

Travis CI: disable automake silent rules

---

.gitignore
.travis.yml
configure.ac
data/Makefile.am
data/check-files-in-git.sh
data/check-svg-exists.sh
data/layouts/Makefile.am

Easier to test, comment, write, and review when it's in a separate file.
The automake integration is a bit odd. We can't pass arguments to scripts but
the only sane way for that script is to take the top_srcdir as argument
(otherwise it'd have to be a configure.in script). We can't do that, but we
can set it in the environment for the tests so that's the next best thing.
This also drops the custom lookups for git, grep and sed. Just make sure it's
in your PATH. Where git ls-files fails, the test is skipped which should make
anyone curious. This also covers the case where git is not available, so
that's not a hard failure.

data: move the git and svg checks to a separate scripts

---

tools/show-svg-image.c

Leaving 'error' uninitalized causes the librsvg to believe that Something
Bad (TM) has already happened and prevents it from working.
(lt-show-svg-image:18442): librsvg-CRITICAL **: 14:34:08.414: rsvg_handle_write: assertion 'error == NULL || *error == NULL' failed
Fixes: https://github.com/linuxwacom/libwacom/issues/103

Prevent librsvg from bailing at the sight of uninitialized data

---

data/elan-264c.tablet

This update improves the support of styli and use a more generic name.

elan-264c: add both pens with and without eraser support

---

libwacom/libwacom-database.c

Several tests fail when running on a system with the musl libc library
with the error "Duplicate match of 'usb:256c:006e' on device 'Huion H420'".
The root cause appears to be musl's handling of '%63c' in our format string.
Specifically, unlike glibc which interprets this to mean "read up to 63
characters", musl interprets it as "read exactly 63 characters".
This commit tweaks our format string to extract the first three required
fields and probe (with ':%n') to see if more data follows. In such a case
we can directly strdup the remainder of the string.
Ref: https://github.com/linuxwacom/libwacom/issues/85

Fix parsing of match strings when using musl

---

.travis.yml
Makefile.am
data/Makefile.am
data/check-data-in-meson.build.sh
meson.build
run-full-test.sh
test/valgrind.suppressions

This adds the meson build system in addition to the automake bits we already have. Meson allows for a much easier to understand build system description, it's faster and many of the upstream projects we care about are already using it (libinput and GNOME in large parts).
Long-term I'd like to remove autotools but I understand that this may be off a few releases at least.

Add support for the meson build system

---

.travis.yml

This line is only executed in the coverity bits, so that string is always
nonzero and we don't need to test for it

travis CI: remove a now-obsolete condition

---

tools/show-svg-image.c

This broke with newer librsvg because the encoding with g_markup_escape_text
left us with # in the data. That now gets (correctly) interpreted as URL
fragment identifier and discarded, see
See https://gitlab.gnome.org/GNOME/gtk/issues/1471

tools: base64-encode the svg data

---

data/intuos-s-p3.tablet

Without the EvdevCodes specified, the buttons of the tablet are not
taking effect. This is visible with e.g. the gnome-control-center wacom
tablet configuration panel.
After adding the EvdevCodes, the buttons presses are properly detected
and can be bound to specific actions.
Signed-off-by: Paul Kocialkowski <contact@paulk.fr>

data: intuos-s-p3: Add EvdevCodes to description to support buttons

---

meson.build

meson.build: match the libwacom.pc file Name with the autotools one

---

data/elan-2628.tablet
meson.build

Hi!
This tablet is also found on some HP Envy x360 ag0xxxx (including mine). This commit is basically just a copy of  #95 (thanks @daenney !) modified to match this device.

Add support for ELAN 2628

---

data/isdv4-50ef.tablet
meson.build

Ref: https://github.com/linuxwacom/wacom-hid-descriptors/issues/68

data: Add ISDv4 50EF (Lenovo YOGA 720-13IKB)

---

meson.build
meson_options.txt

Nice to have for distributions, which needs to have predicable build.
Signed-off-by: David Heidelberg <david@ixit.cz>

meson: make docs configurable

---

run-full-test.sh

The `git rebase` todo list allows you to specify scripts to be run as
part of the rebase process. This can be used e.g. to make sure that
the test suite still passes after any change to a commit in the history.
The `run-full-test.sh` script doesn't work properly when called by
`git rebase`. The script wants to perform a temporary checkout of the
repository for some of its tests, but this can fail with a "working
tree already exists" error. This is a result of the GIT_WORK_TREE
environment variable being already set by the `git rebase` command.
To work around this, we can just unset the variable since we do not
actually rely on its presence.

Make run-full-test.sh compatible with git rebase

---

data/libwacom.stylus

When the stylus database was initially populated from the kernel's list
of known stylus IDs, it brought over several nonsense IDs that should have
been removed from the kernel ages ago. All EMR styli should have an ID
with bit 0x800 set, and those which don't can be traced back to an almost-
prehistoric version of the kernel driver (commit 268175ce6f in the kernel's
history/history.git repository if you must know). That kernel commit only
used the low byte of the ID, and when the higher bytes were later used
the truncated versions were never removed.
Notably, bit 0x800 is *not* set for puck IDs, so don't assume that they
also need removal ;)

data: Remove nonsense EMR stylus IDs

---

meson.build

If I understand this correctly:
- our deprecated symbols are remapped into a specific library version
- nothing in the test calls those symbols, so they're optimized away (they end
up as local symbols)
- our test uses asm to link to those functions but by then they're already
gone
Rather than fixing this let's just disable the test, it doesn't provide us
with anything useful in the LTO condition anyway.
Fixes #152

meson.build: disable the deprecated symbols test with LTO

---

data/isdv4-51e2.tablet
meson.build

Ref: https://github.com/linuxwacom/wacom-hid-descriptors/issues/71

data: Add ISDv4 51E2 (Lenovo Yoga C940-14IIL)

---

data/isdv4-51be.tablet
meson.build

Second known PID for this tablet PC model.
Ref: https://github.com/linuxwacom/wacom-hid-descriptors/issues/61

data: Add ISDv4 51BE (Lenovo X1 Yoga 4th)

---

data/isdv4-51af.tablet
meson.build

Ref: https://github.com/linuxwacom/wacom-hid-descriptors/issues/72

data: Add ISDv4 51AF (Lenovo ThinkPad X390 Yoga)

---

data/mobilestudio-pro-16-3.tablet
meson.build

MobileStudio Pro devices which are sent in for repair may be returned with
an entirely new pen and touch sensor. These new sensors are distinguished
from original hardware with a new PID.

data: Add new MobileStudio Pro sensor PID

---

data/elan-29a1.tablet
data/elan-29b6.tablet
meson.build

the [ASUS ZenBook Pro Duo UX581GV](https://www.asus.com/Laptops/ZenBook-Pro-Duo-UX581GV/Tech-Specs/) has two internal screens - 
- top/main oled screen (345mm x 194mm → 13.59in x 7.64in)  ELAN 29B6
- bottom/secondary TFT screen (345mm x 99mm → 13.59in x 3.9in) ELAN 29A1
both with touch and pen support.

data: Add ELAN 29B6 & 29A1 (ASUS ZenBook Pro Duo UX581GV)

---

data/wacom-one.tablet
meson.build

Add .tablet file and add it to meson.build.

data: Add support for Wacom One Pen Display 13

---

data/isdv4-51f6.tablet
meson.build

Ref: https://github.com/linuxwacom/wacom-hid-descriptors/issues/78

data: Add ISDv4 51f6 (ThinkPad L13 Yoga)

---

meson.build
meson_options.txt

Brings it in-line with the documentation feature (see 18722d3) so to disable
the tests, run meson -Dtests=disabled, as opposed to the previous
-Dtests=false.
No real reason other than cosmetics here.

meson_options: make the tests a feature too

---

test/test-tablet-validity.c

* Supersedes pull requests #197 and #199 to add a test which checks for the wireless dongle.
* Allow matches to non-zero VID:PID for serial devices as mentioned in #199 
* Expand VID:PID checks to all defined matches

Several test suite updates

---

data/isdv4-2d1f-001e.tablet
meson.build

Ref: https://github.com/linuxwacom/wacom-hid-descriptors/issues/82
Ref: https://github.com/linuxwacom/xf86-input-wacom/issues/97

data: Add ISDv4 2D1F:001E (Samsung Notebook 9 Pro)

---

data/isdv4-48ec.tablet
meson.build

Wacom touchscreen from the 2019 Dell XPS 13 2-in-1 (7390). Listed in libinput as:
```
Device:           Wacom HID 48EC Pen
Kernel:           /dev/input/event11
Group:            5
Seat:             seat0, default
Size:             288x180mm
Capabilities:     tablet 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      identity matrix
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Accel profiles:   none
Rotation:         n/a
Device:           Wacom HID 48EC Finger
Kernel:           /dev/input/event12
Group:            5
Seat:             seat0, default
Size:             288x180mm
Capabilities:     touch 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a …
```

Support Wacom HID 48EC (Dell XPS13 7390 alternate)

---

data/isdv4-51f5.tablet
meson.build

Ref: https://github.com/linuxwacom/wacom-hid-descriptors/issues/83

data: Add ISDv4 51F5 (Lenovo ThinkPad L13 Yoga)

---

meson.build

[Found](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=244554) downstream. libxml2 dependency has been there for ages but Meson made it mandatory.

Unbreak Meson build if libxml2 is not installed

---

data/Makefile.am
data/layouts/Makefile.am

See find(1) manpage on [DragonFly](https://www.dragonflybsd.org/cgi/web-man?command=find&section=1), [FreeBSD](https://man.freebsd.org/find/1), [NetBSD](https://netbsd.gw.com/cgi-bin/man-cgi?find+1+NetBSD-current) [OpenBSD](https://man.openbsd.org/find.1). While build doesn't actually fail despite errors some files end up not being installed e.g., https://github.com/freebsd/freebsd-ports/commit/eea904e27f1b

Unbreak autotools build on BSDs

---

data/check-data-in-meson.build.sh
data/check-files-in-git.sh
data/check-svg-exists.sh
run-full-test.sh

<details><summary>Tests output</summary>
```
$ cc --version
FreeBSD clang version 10.0.0 (git@github.com:llvm/llvm-project.git 90c78073f73eac58f4f8b4772a896dc8aac023bc)
Target: x86_64-unknown-freebsd13.0
Thread model: posix
InstalledDir: /usr/bin
$ meson _build
$ ninja -C _build test
ninja: Entering directory `_build'
[0/1] Running all tests.
1/10 libwacom:all / files-in-git             OK       0.81 s
2/10 libwacom:all / svg-layout-exists        OK       1.06 s
3/10 libwacom:all / data-files-in-meson.build  OK       0.25 s
4/10 libwacom:all+valgrind / test-load       OK       0.14 s
5/10 libwacom:all+valgrind / test-dbverify   OK       0.25 s
6/10 libwacom:all+valgrind / test-tablet-validity  OK       0.15 s
7/10 libwacom:all+valgrind / test-stylus-validity  OK       0.05 s
8/10 …
```

Unbreak tests on FreeBSD

---

data/isdv4-5044.tablet

Fix the incorrect width. Sensor is 27648 units wide with a resolution
of 2540 lpi.
Ref: https://github.com/linuxwacom/wacom-hid-descriptors/issues/88

data: Fix ISDv4 5044

---

data/layouts/huion-h420.svg

Noticed this minor typo while looking for layout examples. As far as I can find, the H410 is not an existing device, and most likely a typo.

data: fix typo in Huion H420 SVG title

---

data/huion-420.tablet

I've omitted a layout SVG, since this tablet has no buttons or anything but the active area. Hopefully that's alright, if not I can make one. `Styli` was copied over from the H420 definition.

data: Add Huion 420

---

data/gaomon-s56k.tablet

This PR adds a tablet definition for the [GAOMON S56K tablet](https://www.amazon.ca/GAOMON-Graphics-Drawing-Portable-Battery/dp/B01LL2QGXA) (thanks to @kiritofeng who let me prod it remotely).
If I understand the `Reversible` parameter correctly, this tablet isn't.
This tablet seems pretty weird to me... it masquerades as a Huion (vendor `256c`) despite not being the same manufacturer, and the pen is visually identical to my Huion 420's. Since it is, I just copied the `Styli` from the Huion 420 definition.
The device names in general just seem to have `s/Huion/Tablet Monitor/g` applied. I noticed `65-libwacom.rules` in systemd had:
```
ATTRS{name}=="HUION * Consumer Control", GOTO="libwacom_end"    
```
I'm not sure if that should be adjusted for this tablet, but thought I'd mention it. …

data: add GAOMON S56K tablet definition

---

data/volito-4x5.tablet

A pretty ancient and simple (it has a pen with no eraser and only one button) device but in the pre-libinput (or perhaps legacy-driver) days it worked perfectly - I was able to, out of the box, draw with varying pressure in the GIMP and the on-stylus button correctly worked as the right-mouse button. Getting it to work on a modern system took some work (in case anyone is interested, turns out that in order to both have the driver trigger button-1 events on contact with the tablet surface rather than as soon as the stylus came into proximity, and to get any pressure readings other than 1 once down, I had to change the threshold from the default 26 to 5 _exactly_ - no other value I have tried seems to have any effect) but in the end it does work too, and as a bonus it seems the generic …

Support Wacom Volito 4x5 (FT-0405, 056a:0060)

---

data/isdv4-51f6.tablet

Signed-off-by: Jason Gerecke <jason.gereke@wacom.com>

data: Correct tablet name for ISDv4 51F6 (was: F1F6)

---

tools/65-libwacom.rules.in

For instance, a GAOMON S56K device exposes "Tablet Monitor Consumer
Control" and "Tablet Monitor System Control" devices, both of which are
not tablet devices.
Instead of listing the Cartesian product of [HUION, TabletMonitor] &times; [Consumer Control, System Control] (as far as I can tell the udev syntax doesn't allow regex-like groupings?), I relaxed the matching to exclude all Consumer/System Control devices. I can write the Cartesian product directly if that's preferred, though.

tools: expand Huion consumer control quirk to include GAOMON

---

tools/list-compatible-styli.c
tools/list-devices.c

See [error log](https://github.com/linuxwacom/libwacom/files/4639598/libwacom-1.3.log) caused by the following flags
https://github.com/linuxwacom/libwacom/blob/fbf519f76e235e4f465ae2f91066415f49c74318/.travis.yml#L22

Unbreak -Werror on FreeBSD

---

data/elan-2514.tablet

Found in HP Spectre x360 13-aw0xxx series.
Changes modeled after #95, the tablet is now recognized in Gnome's settings (but the stylus isn't).
`xsetwacom --list` still shows no devices.

Tablet config for Elan 2415

---

libwacom/libwacom.sym

The version number is technically meaningless since it's just a string. But we
try to keep it in sync with the version the API was introduced in.

Fix the version number for the new API

---

data/huion-new-1060-plus.tablet
data/layouts/huion-new-1060-plus.svg

This adds the Huion New 1060 Plus. I've tested this with the equivalent Gaomon M106K but I've added this as Huion as these seem to be more common. The layout for the Gaomon is be very similar: it has round buttons instead of rectangular buttons but they're in the same locations, so I don't think it's worth the effort to create a different layout file (and I'm not willing to spend any more time on tuning SVGs ;)).
There are a few things where I'm not 100% sure, I'll comment inline.

Add Huion New 1060 Plus

---

libwacom/libwacom.c
libwacom/libwacom.h
test/test-load.c
test/test-tablet-validity.c

To my knowledge, they are not used by anyone outside libwacom itself (which
uses it to set up default button mappings where EvdevCodes is missing) and
their usefulness has degraded over time anyway (any post-I5 device is now also
Intuos5) and the vast majority of devices now are ISDV4. So for any device
bought in the last few years, it's either Cintiq, Intuos5 or ISDV5.
And non-Wacom tablets are even harder to categorize.
Let's deprecate this so if there are any users, they get a compiler warning
about it at least.

Deprecate the WacomClass in the API

---

data/intuos-m-p3-wl.tablet
data/intuos-m-p3.tablet

The buttons do not send 0x110-0x114, as already commented in the file:
Buttons are no loger RIGHT, LEFT, FORWARD, and BACKWARD.
The buttons are now reported as numbered buttons as with
the Intuos Pro series.
The heuristics in set_button_codes_from_heuristics() default to the
LEFT/RIGHT/...  buttons for Class=Bamboo though, so let's set the codes
explicitly.
Fixes #5 
cc @martinhath, it was faster to quickly fix this here than making you go through another fix/push/review cycle.

data: fix button codes for the 6100WL

---

meson.build

A tarball generated with autotools has a generated Makefile.in in every
directory we have a Makefile.am. Using install_subdir() we end up installing
that file unless we explicitly exclude it. This doesn't happen when building
from git (unless the git tree is dirty from a previous autotools setup).
And sneak a "space before tab" whitespace change in while we're in that
vincinity.

meson.build: ignore Makefile.in when installing data

---

data/isdv4-48d6.tablet

Add AES sensor used by the HP ZBook Studio x360 G5.
Tested with the HP Rechargeable Active Pen G3 (0x826B). Aside: I noticed that this stylus is listed in #178 without a name; is there some info I could provide to document it better?
For reference, I've attached [record_1589605219.tar.gz](https://github.com/linuxwacom/libwacom/files/4637982/record_1589605219.tar.gz) produced by [the caputure.sh script](https://gist.githubusercontent.com/jigpu/b7b47e4bede584cec8562f666fd84af4/raw/af36c0a0fc2c019750472443369915ad7ea97737/capture.sh).

Add HP ZBook Studio x360 G5 Wacom AES sensor 48d6

---

tools/65-libwacom.rules.in

This was not doing actual matching of the property, but assigning it,
which resulted in no device being assigned this property. This broke
gamepad/joystick permissions.
Fixes #271

tools: Fix joystick property matching in udev rule

---

.travis.yml
meson.build

Let's use something 2 years old instead of 4 years old! Travis still defaults
to 16.04 and 20.04 is not (yet?) available.

travis: update to bionic (ubuntu 18.04)

---

data/isdv4-4838.tablet
data/isdv4-4851.tablet
data/isdv4-4957.tablet

The wacom-hid-descriptors script to autogenerate tablet definitions from
sysinfo data was not updated to add a Styli line in its output after
libwacom began supporting AES styli. Autogenerated definitions added after
the addition of AES support need manual updating.
The autogeneration script has since been updated to add the Styli lines.

data: Add "Styli=@isdv4-aes;" to new AES devices

---

.travis.yml

Hi,
I have added support for ppc64le build on travis-ci in the branch . The travis-ci build log can be tracked on the link :https://travis-ci.com/github/sanjay-cpu/libwacom . I believe it is ready for the final review and merge.
Please have a look on it and if everything looks fine for you then please approve it for merge.
Thanks !!

Added support ppc64le

---

.travis.yml

deprecated and has no effect, as the travis CI helpfully points out

travis CI: drop root: sudo

---

libwacom/libwacom.c
libwacom/libwacom.h
test/test-load.c

The term 'usbid' here is misleading in the API and it's not worth adding
separate functions (or a new generic function) for the other busses. Where the
vid/pid matches, return the device for any bus (except the vid/pid-less serial
bus).

When loading devices for a vid/pid, fall back to bluetooth and i2c

---

data/elan-2514.tablet

HP Envy x360 Convertible 13-ay0xxx
sysinfo.L1vXaj9Wcz
https://github.com/linuxwacom/wacom-hid-descriptors/issues/110

Add support for ELAN-2514 variant i2c:04f3:2af4

---

tools/65-libwacom.rules.in

Summary: we expect add, change or remove but kernel 4.12 added bind and
unbind. These events were previously discarded by udevd. Our rules should
handle any event *but* remove, so update as suggested in the announce email
linked below.
For a longer explanation, see the system 247rc2 announcement
https://lists.freedesktop.org/archives/systemd-devel/2020-November/045570.html

tools: update rules to handle bind/unbind events

---

.github/workflows/freebsd.yml
.github/workflows/main.yml

Travis CI is about to severely limit the free tiers. Specifically, we would
get 1000 minutes (which at current use would last us a few months) but once
they're up, we have to request more on a case-by-case basis.
This is not workable.
Switch to GitHub actions instead. This patch convers the autogen, meson and
build-from-tarball parts over.
It does **not** provide:
- ppc64le
- ~~FreeBSD~~ *edit: implemented as VM run on macos*
- coverity
In the ppc64le ~~and FreeBSD~~ case I don't know how how to get those working, cc @sanjaymsh, @jbeich 
There doesn't seem to be any available runners for either of those.
Coverity is just a matter of porting from travis to the github action syntax.
~~The travis.yml file is removed despite the above missing items, git will
provide its content for future …

Replace Travis CI with GitHub Actions

---

data/xp-pen-g640.tablet

The PID of my XP-Pen Star G640 is 0094, not 0914. My tablet only shows up in the Wacom Tablet settings if I make this change.

Add second PID for XP-Pen Star G640

---

data/isdv4-5148.tablet

Hi,
I was able to get the tablet to be recognized but the buttons on the stylus don't seem to be working as configured in the settings application. The bottom button, closest to the tip, does nothing when pressed. The top button, when pressed acts as a back button. 
Note: I have also opened a issue in linuxwacom/wacom-hid-descriptors with the system information: https://github.com/linuxwacom/wacom-hid-descriptors/issues/117

data: Add Lenovo X1 Yoga 3 Generation (ISDv4 5148)

---

data/elan-2514.tablet

Used in HP Spectre x360 13-ap0xxx
See also the sysinfo in https://github.com/linuxwacom/wacom-hid-descriptors/issues/127.

data: Add support for ELAN-2514 variant 04f3:2813

---

data/elan-2514.tablet

Tablet definition for HP Spectre x360 Convertible 15-df0xxx (04f3:2817)
more info: [https://github.com/linuxwacom/wacom-hid-descriptors/issues/70](https://github.com/linuxwacom/wacom-hid-descriptors/issues/70)

data: add support for HP Spectre x360 Convertible 15-df0xxx (04f3:2817)

---

.github/workflows/main.yml

Otherwise we are trying to pull down old packages and failing with 404s

workflows: run apt update + install instead of apt-get

---

.github/workflows/main.yml
libwacom/Makefile.am
libwacom/libwacom-database.c
meson.build
test/test-dbverify.c

To add a new .tablet file, a user would have to add that file to /usr/share.
This location may be read-only on some systems, and any file there will
conflict with files provided by the distribution package. In the best case,
the user's file will be overwritten on update, in the worst case a file name
change leaves both files in place, causing conflicts.
The traditional approach is to have distribution-provided files in /usr and
host-specific packages in /etc, so let's do the same here: add /etc/libwacom
as default lookup path for .tablet and .stylus files.
The CI is a bit quirky again because afaict github workflows don't do templates. So it's some duplication but the basic summary is:
- build and install everthing with prefix `/usr`
- generate a list of supported devices with the …

Support loading tablet/stylus files from /etc/libwacom

---

data/elan-2514.tablet

I have an HP Envy x360 (2020) convertible laptop, with model number 15z-ee000.  This laptop has an ELAN2514 wacom layer, but with a different device identifier than those defined in the elan-2514.tablet file.  I went ahead and added the device identifier to the tablet file and it worked out of the box for me.
The command `libinput list-devices` outputs the following on my 15z-ee000:
```
Device:           ELAN2514:00 04F3:2B0A
Kernel:           /dev/input/event9
Group:            9
Seat:             seat0, default
Size:             332x188mm
Capabilities:     touch 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      identity matrix
Scroll methods:   none
Click methods:    none …
```

Add ELAN 04F3:2B0A to ELAN 2514 definition file

---

data/elan-2514-alt2.tablet

This is based on #286 with a similar file-name structure.  I also contributed the sysinfo as an issue on wacom-hid-descriptors.
Let me know if there are any changes needed.

Data: Add ELAN 2514 variant i2c:04F3:29CF (HP ENVY x360 Convertable 15-dr1xxx)

---

data/hp-pro-tablet-408.tablet

Link: https://github.com/linuxwacom/wacom-hid-descriptors/issues/137

data: Add support for the HP Pro Tablet 408

---

meson.build
tools/Makefile.am
tools/show-stylus.py

This is an interactive tool to allow users to easily find their stylus IDs.
libinput debug-tablet provides something similar but it's useful to have this
as part of our own repository.
Example output from running without arguments:
$ sudo libwacom-show-stylus
Using "Wacom Intuos Pro M Pen": /dev/input/event23
Tool id 0x842 serial 0x748012bf in-proximity: False
Tool id 0x84a serial 0x748012bf in-proximity: False
edit: with the second commit, it now also adds this:
```
Suggested line for .tablet file:
Styli=mobilestudio
```
i.e. it loads `libwacom.stylus` and matches the ids with the groups.
cc @jigpu for input please. autotools integration is missing but otherwise this seems like a good addition?

tools: add a libwacom-show-stylus tool to easily check for stylus IDs

---

data/huion-h640p.tablet
data/layouts/huion-h640p.svg

The tarball with the data is in queue to be accepted: https://github.com/linuxwacom/wacom-hid-descriptors/issues/145
Both the `.tablet` and `.svg` files are forks of the respective huion h950p variants

Support for Huion h640p

---

.github/actions/meson/action.yml
.github/actions/pkginstall/action.yml
.github/actions/pkginstall/install-apt.sh
.github/actions/pkginstall/install-pip.sh
.github/workflows/main.yml

Two github actions are added: pkginstall and meson. They can be trigged with
uses: in the CI jobs and standardize the package installs and meson setup
jobs. This cuts down on duplication and in theory the same actions can be used
by xf86-input-wacom later.
A few noteworthy behaviors:
- the postgres package repo has to be disabled, it causes random CI failures
with a 404
- the precmd approach is a bit weird but it's the easiest way to use sudo on
demand.
- every `run:` command starts a new shell, so we can't easily export variables
between the various steps
cc @jigpu

Github CI: use a custom actions installing and meson building

---

README.md

We no longer have a ruleset, we're using the hwdb now - update accordingly.
Fixes #364 (hopefully)

README: fix the udev instructions

---

.github/workflows/freebsd.yml

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=253815 will replace `py37-pip` with `py38-pip`. While `devel/py-pip` will work other Python packages may not be under `devel/` directory (or physical category), so let's use `-g` to enable glob expansion of `*`, `?`, `[`.

CI: unhardcode pip and install python3 symlink

---

libwacom/libwacom-database.c
tools/list-devices.c

This reduces the device list from currently 423 to a more reasonable 329, for 302 .tablet files.
There is still some duplication due to how we print and list devices - any device with more than one bustype will be listed once per bus type. But at last it will no longer be listed once per match entry per bus type (e.g. ISDv4 90 had 4 entries before).

De-duplicate the device list returned by the database

---

.github/workflows/main.yml
libwacom/libwacom-database.c
meson.build
tools/Makefile.am
tools/generate-hwdb.c
tools/libwacom-list-devices.man
tools/list-compatible-styli.c
tools/list-devices.c

This sits on top of #368
We had the `list-devices` tool for a while but it didn't get installed. Let's install it and change the output format to a matchstring(-ish) based oneline format. Having this tool makes it easier to answer the question "is my device supported" or, in the case of #367, "is my tablet file being picked up".
Fixes #367

Install libwacom-list-devices and change to a oneline format

---

meson.build

As of 0.49, using / is equivalent to join_paths(). But it's a lot more
readable.

meson.build: use / instead of join_paths

---

.github/workflows/main.yml
libwacom/libwacom-database.c
libwacom/libwacom.c
libwacom/libwacomint.h
tools/list-devices.c

This enables a user to copy/paste a `.tablet` file to `/etc/libwacom/`, change the `DeviceMatch=` line and have it magically work, even if the original file still exists in `/usr/share/libwacom`.
Previously we failed with an error about this being a duplicate - that error is still there but only if duplicate matches are used within the same data directory.
Fixes #379
cc @Big-FG

Allow duplicate devices as long as they're in separate data dirs

---

libwacom/libwacom.c

Added in glib 2.62, a bit too new for us.
Fixes #386

Avoid using g_array_copy

---

data/test_data_files.py
meson.build

We don't want any .tablet entries with the receiver ID as that may match
multiple devices. We already test this as part of the tablet-validity test
(see 134166f) but it's a bit more obivous this way.
cc @jigpu

data: add a test for receiver IDs

---

.github/workflows/freebsd.yml

Clock desync due to running under a VM confuses Meson. Noticed via https://github.com/intel/libva/commit/fae0a978c304961b670027f644fb9305c009a9bd

CI: unbreak FreeBSD build

---

.github/actions/pkginstall/install-apt.sh

Apparently that file is no longer there, so let's hope things work without the
hack.

CI: remove the postgres apt sources hack

---

.github/workflows/main.yml
tools/libwacom-list-devices.man
tools/list-compatible-styli.c
tools/list-devices.c
tools/list-local-devices.c

Let's output something that is both human- and machine-readable. This makes
it easier to search for specific devices with YAML parsers, e.g. to select all
bluetooth devices one could use:
``
$ libwacom-list-devices | yq '.devices[] | select(.bus == "bluetooth") | .name'
``
Output for list-devices is now:
```
devices:
- {bus: i2c, vid: '056a', pid: '5169', name: Wacom ISDv4 5169}
...
```
Output for list-local-devices is now for example:
```
devices:
- name: 'Wacom Intuos Pro M'
bus: usb
vid: '056a'
pid: '0357'
nodes:
- /dev/input/event24
- /dev/input/event23
- /dev/input/event22
```

tools: use a YAML-compatible format by default

---

meson.build
test/test-dbverify.c

Race condition: pytest collects files at the same time as `test-dbverify` adds/removes them. In some cases, this can cause a race where pytest fails to open a file that has since been removed.

Fix a pytest-related test error

---

configure.ac

Use LT_INIT which is the replacement for AC_PROG_LIBTOOL. That takes a
disable-static argument to disable the creation of libwacom.a. Static
libraries were never really supported anyway, let's not install those.

configure: disable static libraries

---

data/kamvas-pro-13.tablet
data/layouts/kamvas-pro-13.svg

The tablet also has a touch strip that doesnt seem to be recognized, possibly related to #361. Note that this has the same device ID as the Gaomon S56K.
sysinfo tarball: [here](https://github.com/linuxwacom/wacom-hid-descriptors/issues/160)

data: add Huion Kamvas Pro 13

---

tools/libwacom-update-db.py

Non-Wacom devices often have a Keyboard device node for the pad instead
of a real pad node. The same devices often share the USB IDs so the
keyboards get caught up by the main tablet rule. Assigning
ID_INPUT_TABLET to a keyboard means libinput won't load them because
they don't look like a keyboard.
Fix this with a non-wacom catchall rule: any device node ending in
Keyboard has ID_INPUT_TABLET removed again.
Fixes #409 
cc @tviel can you test this please with your device?

tools: remove ID_INPUT_TABLET from "foo Keyboard" devices

---

data/elan-2ad9.tablet

This configuration makes the tablet & stylus show up in gnome settings.

data: add support for ELAN-2AD9 in HP ProBook x360 435 G7

---

data/waltop-slim-tablet-12-1.tablet

This .tablet-file worked for my "Medion Graphics Pad MD 85637" just fine. Nevertheless I realised that it is a re-branded tablet so I used the "original" name. 
I also found out that many companies used this exact model with seemingly the same USB ID but I wasn't able to confirm that.
Further I wasn't able to add support for some software buttons yet. I'm not sure whether this is even possible or not. The tablet itself and the settings I used are working though.
I found the mentioned information [here (Link to DIGImend)](https://digimend.github.io/tablets/Waltop_Slim_Tablet_12.1_inch/).

data: add support for Waltop Slim Tablet 12.1" and rebrands

---

data/intuos-m-p3-wl-android.tablet
data/intuos-m-p3-wl.tablet
data/intuos-s-p3-wl-android.tablet
data/intuos-s-p3-wl.tablet

Adds the new Intuos BT model ID's into the relevant .tablet files.

Add new Intuos BT (CTL-4100WL/CTL-6100WL) device matches

---

data/isdv4-484e.tablet

Just recently received a Dell Latitude 5290 and noticed the internal tablet missed a description file.
This is a copy of the file for it's predecessor, the Latitude 5285, with updated device id, making it recognized by, for example, Gnome's settings.

Add tablet description for Dell Latitude 5290

---

libwacom/libwacom.c

umockdev doesn't support mocking device nodes, so libwacom_new_from_path()
fails to find devices after calling g_udev_client_query_by_device_file()
that always fails as it cannot stat() the device node to get its type
and major and minor numbers.
Using this reimplementation of g_udev_client_query_by_subsystem_and_device_file()
(see https://gitlab.gnome.org/GNOME/libgudev/-/merge_requests/22),
no I/O is made at all, and all the data comes from the mocked udev database.
Closes: #438
Signed-off-by: Bastien Nocera <hadess@hadess.net>

Fix libwacom_new_from_path() failing in mocked environment

---

data/isdv4-ec.tablet

This devices is used in the Thinkpad Yoga 260, together with an Elan
touchscreen, see
https://gitlab.freedesktop.org/libinput/libinput/-/issues/690
Since we don't yet have a PairedID entry for this device, let's add one
now - shouldn't hurt on the original device(s) with the EC tablet.

data: add a PairedID for the ISDv4 EC

---

tools/libwacom-update-db.py

The (broken) rename to 66-libwacom.hwdb was motivated from a version
of this tool that didn't yet have the --buildsystem-mode. Let's get rid
of the check and always write out a filename that won't overwrite the
system-provided ones.

tools: always write out custom hwdb files as 66-libwacom.hwdb

---

.github/actions/meson/action.yml

meson setup takes a srcdir argument, so let's use that instead

CI: drop the pushd srcdir from the meson action

---

libwacom/libwacom.h

Should've been libwacom_is_builtin() but that is deprecated now, so
let's switch to libwacom_get_integration_flags() instead.
Fixes #450

doc: fix the check for integration flags in the example code

---

.github/workflows/freebsd.yml

And use macos-10.15 as requested in the README
Maybe this resolves the freebsd unreliability

github: bump freebsd workflow to 0.1.5

---

data/surface-go-2.tablet

Link: https://github.com/linuxwacom/wacom-hid-descriptors/issues/192
The tablet definition couldn't automatically be created. I manually created this file, based on https://github.com/linuxwacom/libwacom/pull/352 and the output from `libinput list-devices`. After adding to `/etc/libwacom` and running `libwacom-update-db` I was able to configure my stylus in Gnome Settings.

data: Add Microsoft Surface Go 2

---

.github/actions/meson/action.yml
.github/workflows/main.yml
libwacom/libwacom-database.c
meson.build
test/test-dbverify.c

This also updates the `meson` github action to use `ninja --verbose` which will affect builds of `xf86-input-wacom` (since they just grab that from libwacom master).
The biggest change is: [CI: don't enable -Wall -Wextra in the CI](https://github.com/linuxwacom/libwacom/commit/3e4041b9ca556d4dabc145add4a631bc008a9fd2)
This is a leftover from autotools builds, meson uses the warning_level
option for this. The net result of our CFLAGS being appended was this
sequence: `-Wall -Wextra -Wno-foo -Wall -Wextra`
The second set of `-Wall -Wextra` undid all the `-Wno-foo` we carefully
selected in `meson.build` - at least with clang, possibly with gcc too.
cc @jigpu because it probably matters for https://github.com/linuxwacom/xf86-input-wacom/pull/254

Fix a few compiler warnings

---

.github/workflows/main.yml

0.62.0 fails meson dist with a python complaint, which has been fixed
upstream. But until pip pulls down a fixed version, let's pin meson.
See issue https://github.com/mesonbuild/meson/issues/10181

CI: pin the meson version to 0.61.4

---

.github/workflows/main.yml

pip now pulls down meson 0.62.1 with this issue fixed, so let's revert
this.
This reverts commit 7ff829e07622bb01daaad643f981d29e878a063a.
Reverts #489, meson bug in question: https://github.com/mesonbuild/meson/issues/10181

Revert "CI: pin the meson version to 0.61.4"

---

data/isdv4-5155.tablet

I installed Fedora 36 on my Lenovo 20LHS04L00 ThinkPad X380 Yoga and noticed that whilst it seemed to (partially) work, it didn't show up in GNOME Wacom settings.
After a lot of looking around and googling I found these related links (issue and PR) implying that the laptop was supported.
https://github.com/linuxwacom/wacom-hid-descriptors/tree/master/Lenovo%20ThinkPad%20X380%20Yoga
https://github.com/linuxwacom/wacom-hid-descriptors/issues/38
However my device was not being picked up by:
```
$ libwacom-list-local-devices
/dev/input/event8 is a tablet but not supported by libwacom
Failed to find any devices known to libwacom.
```
`evtest` reported the following:
```
/dev/input/event7:	Wacom Pen and multitouch sensor Finger
/dev/input/event8:	Wacom Pen and multitouch sensor Pen
...
Input …
```

Add tablet file for 5155 version of Lenovo X380

---

tools/65-libwacom.rules.in

Just like the Consumer Control and other special names we already match,
the device's Keyboard node should not be a tablet we need to handle.
Extracted from #288 so we can track regressions for this separately.
cc @lucalandolfi

tools: don't match "* Keyboard" devices

---

data/huion-hs611.tablet
data/layouts/huion-hs611.svg
tools/65-libwacom.rules.in

This adds initial support for the Huion HS611. All the buttons could be mapped inside GNOME settings, except for the Touch Strip. The layout includes the strip anyway because it works and it could be remapped using `xsetwacom` like this
```
xsetwacom set "HUION Huion Tablet_HS611 Touch Strip pad" "AbsWheelUp" "key ctrl shift ="
xsetwacom set "HUION Huion Tablet_HS611 Touch Strip pad" "AbsWheelDown" "key ctrl -"
```
I'm still trying to figure it out. The strip is remapped using `AbsWheelUp` and `AbsWheelDown`, like a Touch Ring, and not `StripLeftUp` and `StripLeftDown` like I would have guessed. This could be the reason GNOME couldn't remap the strip.
This also includes a change to the udev rule. If `ID_INPUT_TABLET` is set to 1 for the Keyboard device, the last two buttons, "Switch …

Huion HS611

---

data/huion-kd100.tablet
data/layouts/huion-kd100.svg

Add support for Huion MiniDial KD100

---

data/layouts/xp-pen-artist12.svg
data/xp-pen-artist12.tablet

Although my XP-Pen Artist 12 (mostly) worked under Arch Linux with Gnome 42, it didn't show up in gnome settings.
According to this issue https://gitlab.gnome.org/GNOME/mutter/-/issues/1272, the solution is to add the tablet's definition here.
Right now adding `xp-pen-artist12.tablet` and `layouts/xp-pen-artist12.tablet` to `/etc/libwacom`, running `libwacom-update-db /etc/libwacom` and re-plugging the device adds it to the gnome wacom settings, though the option to remap the keys is missing.
Since my attempts to fix this issue have been unsuccessful, I'm opening this PR in search of guidance.

Add support for XP-Pen Artist 12.

---

data/chuwi-minibookx.tablet

Link: linuxwacom/wacom-hid-descriptors#241
This PR adds the configuration file necessary for the Chuwi MiniBook X' built-in touch panel to show up in the GNOME Settings Wacom panel.
One minor note; I have picked a Stylus ID that functionally matches the actual pen (Chuwi's H7 pen), but I am not sure if there is a more correct way of selecting this. With the more generic choices the configuration screens were showing two buttons, but the H7's secondary pen button only works as an eraser switch. Please let me know if there is another stylus I should pick, or if there is some kind of command I can run to help provide relevant information of this specific pen if that isn't already in the descriptors shared separately.
Thank you!

Add Chuwi MiniBook X

---

data/layouts/xp-pen-deco-l.svg
data/xp-pen-deco-l.tablet

Support for this tablet is queued for [Linux 5.20](https://lore.kernel.org/linux-input/nycvar.YFH.7.76.2206151552060.14340@cbobk.fhfr.pm/T/#t) and it'd be nice to support it in libwacom as well.
The HID descriptor info is available in https://github.com/linuxwacom/wacom-hid-descriptors/issues/242.
I hope I got the SVG right :)

Add XP-Pen Deco L

---

.github/workflows/freebsd.yml

The current 10.15 is about to be deprecated,
see https://github.com/vmactions/freebsd-vm/issues/50
Fixes #510

CI: update FreeBSD macos base to macos-12

---

README.md

The README is probably read more often than the wiki, so let's put the
warning there too that libwacom doesn't make the tablet work.

README: minor fixes and a bit of rewording

---

meson.build

Makes things a lot easier to debug in the resulting
meson-logs/testlog.txt
Related to #515

meson.build: run pytest with lots of verbosity

---

.github/workflows/main.yml

Multiple artifacts with the same name only work if they're in the same
job. We use a matrix here, so our resulting artifact is simply whichever
job finished last.

CI: adjust the artifact names according to the job

---

data/isdv4-50a9.tablet

Hi,
Here is a pull request for adding the .tablet file for the Fujitsu U729X.  This one works with my U729X.  I'm not terribly versed in creating pull requests, or making .tablet files.  (This is only the second .tablet file for me.)  So please let me know what else you would like me to do.  This file seems to work just fine, but about all I've done is to submit the wacom-hid-descriptors, make sure the Gnome Settings works for calibrating the tablet and stylus, and verified that it is listed.  
`$ libwacom-list-local-devices
devices:
- name: 'Wacom Pen and multitouch sensor Pen'
bus: 'usb'
vid: '0x056a'
pid: '0x50a9'
nodes: 
- /dev/input/event6
`
The name came from evtest.
`$ sudo evtest
No device specified, trying to scan all of /dev/input/event*
Available devices:
/dev/input/event0: …

Added the new isdv4-50a9.tablet file for the Fujitsu U729X.

---

data/intuos-pro-2-s.tablet

Except PID, everything is the same.
Signed-off-by: Ping Cheng <ping.cheng@wacom.com>

Add support for a new "Intuos Pro Small"

---

data/wacom.example

We require sysinfo for all submitted tablet files, so let's add this to the example file we point users to.
*Note: I've also updated the corresponding [wiki page](https://github.com/linuxwacom/libwacom/wiki/Tablet-Definition-Files)*

data: add the sysinfo to the wacom.example file

---

data/wacom-hid-52fa-pen.tablet

This PR adds a tablet file for the device identified as the "Wacom HID 52FA Pen" (and elsewhere as WACF2200 ). 
I have this device built into my Lenovo Yoga 6 13ALC7, see the matching [issue` at the wacom-hid-descriptors](https://github.com/linuxwacom/wacom-hid-descriptors/issues/275) repository.  
This file makes the device visible to the Gnome Wacom settings dialog - I'm running a pure Wayland system and I don't actually have a compatible stylus to hand, so I can't make any further guarantees than that, but this seems like as much as would be expected from this change.

Add tablet definition for Wacom HID 52FA Pen

---

data/huion-kamvas-13.tablet
data/layouts/huion-kamvas-13.svg

sysinfo: https://github.com/linuxwacom/wacom-hid-descriptors/issues/247#issuecomment-1336314324
Similar issues to #361 in that the USB identifier is shared with the Huion H950P, so I had to edit that tablet definition locally to not match in order for this one to take priority.

Add tablet definition for Huion Kamvas 13 (GS1331)

---

.github/workflows/check-for-sysinfo.yml
.github/workflows/freebsd.yml
.github/workflows/main.yml
.github/workflows/pages.yml

Node 12 is deprecated so let's switch to the newer version https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

CI: update some actions to newer versions

---

data/layouts/xp-pen-deco01-v2.svg
data/xp-pen-deco01-v2.tablet

I've added support for the XP-Pen Deco01 v2.
The SVG is just a copy of the existing XP-Pen Deco L as the layout is essentially the same.
Note to use this you currently need a special version of the DigiMEND driver to support this - details on this in the libinput issue [here](https://gitlab.freedesktop.org/libinput/libinput/-/issues/839). Those changes should be merged to the kernel in the new year.
The relevant sysinfo issue is https://github.com/linuxwacom/wacom-hid-descriptors/issues/276.
Thanks for all the work you do!

Added support for XP-Pen Deco01 v2

---

test/test_udev_rules.py

Fixes https://github.com/linuxwacom/libwacom/issues/515.
Edit: the CI failure seems to be an unrelated issue.

tests: fix failure if system doesn't use systemd

---

data/elan-2514.tablet

Sysinfo: https://github.com/linuxwacom/wacom-hid-descriptors/issues/294
Tried adding the ID ```04f3:23b9``` to the tablet files in ```/usr/share/libwacom```  , KDE Plasma can recognize the screen and stylus (with HP Tilt Pen) . Screen touch, pressure sensetivity and stylus button are work.
The stylus button remap only works under X11, and the system warns the screen "is going to run out of battery".

Add HP Envy x360 Convertible 13-ar0xxx

---

data/isdv4-121a.tablet

I've added support for the Lenovo Ideapad Duet 5i (Ideapad Duet 5 12IAU7).
Sysinfo issue: https://github.com/linuxwacom/wacom-hid-descriptors/issues/278.
Thanks for maintaining this project!

Add support for Lenovo Ideapad Duet 5i (isdv4-121a.tablet)

---

meson.build
tools/list-local-devices.c

An uninstalled version of libwacom-list-local-devices that does not require the database path to be given on the commandline. Makes things a bit more convenient for debugging, same as the existing builddir/list-devices.

tools: add list-local-devices as builddir tool

---

data/huion-h950p.tablet

Huion re-uses the USB IDs for, presumably, fun and profit and the only way we can distinguish them is with name matches. To make things even more fun, *other* vendors like Gaomon re-use Huion's VID/PID too.
For all devices except the H950p we match on name, but this one was the first one introduced so it only matches on VID/PID. As a result, all devices that don't match on the name get matched for the H950p - including the Dial and Touch Strip subdevices of the Gaomon S620 (see #556). For the user this looks like they have a Gaomon device (pen and pad) and a Huion H950p (dial and touchstrip).
Fix this by narrowing down the H950p to the device name too. The name comes from the sysinfo file linked to in the data file.
cc @jconnolly837 from #308
cc @JoseExposito because he *may* have a H950p …

data: narrow down the Huion H950p to include a name match

---

tools/list-local-devices.c

This changes the YAML output of libwacom-list-local-devices but I'm assuming no-one uses this anyway. The new output lists the device name together with the kernel name, e.g.
```
devices:
- name: 'Wacom Intuos Pro M'
bus: 'usb'
vid: '0x056a'
pid: '0x0357'
nodes:
- /dev/input/event21: 'Wacom Intuos Pro M Finger'
- /dev/input/event20: 'Wacom Intuos Pro M Pad'
- /dev/input/event19: 'Wacom Intuos Pro M Pen'
```
This output should make it easier to associate duplicate entries with their respective event node.
Fixes #558

tools: list the kernel name together with the event node

---

data/xp-pen-deco-mini7.tablet

Link to the tablet: https://www.xp-pen.com/product/613.html
[edit by whot: re-using the Deco MW layout here, it's close enough]
Replaces #480 because I can't rebase in github without committing, which means I can't use the new `@generic...` stylus grops.
Two changes compared to #480 
- Re-using the layout from the Deco MW, it's close enough and anyone motivated is free to submit an SVG to fix this properly
- I'm assuming the evdev codes are the same as in the other Deco tablets, let's copy this because we need to define that one for button `E`, otherwise our test suite fails

data: add XP Pen Deco mini7

---

data/isdv4-2d1f-0040.tablet

Link: linuxwacom/wacom-hid-descriptors#318
Fixes: linuxwacom#584

data: Add support for the Samsung Chromebook Plus v2

---

meson.build

Best explanation: 12-ish years ago when I started libwacom, I copied the license from some X11-related repository assuming it was MIT and went with that. Turns out it's actually the HPND-sell-variant: "Historical Permission Notice and Disclaimer - sell variant" https://spdx.org/licenses/HPND-sell-variant.html
No real effects since it's not really that much different to MIT afaict but let's make sure meson prints out the correct SPDX license identifier.
cc @jigpu  @Pinglinux

meson.build: correct license to HPND

---

meson.build
test/test-tablet-svg-validity.c
test/test-tablet-validity.c
tools/list-compatible-styli.c

switch from `strcmp` to the safer `g_str_equal()` and drop a duplicate invocation of pytest

Two minor cleanups

---

data/cintiq-pro-17.tablet
data/cintiq-pro-22.tablet
data/layouts/cintiq-pro-17.svg
data/layouts/cintiq-pro-22.svg

Add tablet and layout files for a new Wacom products.

data: add Wacom Cintiq Pro 22 & 17

---

data/cintiq-pro-13.tablet
data/wacom.example
libwacom/libwacom-database.c
libwacom/libwacom.c
libwacom/libwacom.h
libwacom/libwacom.sym
libwacom/libwacomint.h
test/test-load.c
tools/libwacom-update-db.py

This is parsed but not exported by libwacom itself, at least not until we know what our callers want.
It is used however to determine if a device has a pad and thus used to set the ID_INPUT_TABLET_PAD property through the hwdb. This fixes the issue with some devices without buttons (but with keys) to not get labelled as pads, e.g. the Cintiq Pro 13.
Fixes #585
Note: draft because I need to know the evdev keycodes for the cintiq before we can commit this, cc @Pinglinux

data: add a new Keys/KeyCodes entry to the tablet files

---

.github/workflows/pages.yml

Missing devel dependency added in cc7cc58714a2bf2a7e34e26dab7a6d2f1471c9d2

CI: fix the pages job for the new libevdev dependency

---

data/layouts/xp-pen-artist13-3-pro.svg
data/xp-pen-artist13-3-pro.tablet

Hi! I've created a .tablet and layout file for the [XP-Pen Artist 13.3 Pro](https://www.xp-pen.com/product/artist-13-3-pro.html)
The HID Descriptor is here; [linuxwacom/wacom-hid-descriptors#334](https://github.com/linuxwacom/wacom-hid-descriptors/issues/334)
I tried to create the .tablet file based off of the existing Artist 12 and Deco Pro MW files since those tablets are similar, but I'm not sure if I've done everything right.
The tablet shows up in KDE Wayland's Tablet settings, and everything seems to work except that I can't map any of the tablet's buttons; only the stylus buttons seem to show up. (3 stylus buttons show up, when there are only 2 on the actual stylus)
When I run `libwacom-list-local-devices` I get the following:
```
devices:
- name: 'UGTABLET 13.3 inch PenDisplay' …
```

data: Add XP-Pen Artist 13.3 Pro

---

libwacom/libwacom.c

../libwacom/libwacom.c:498:13: runtime error: null pointer passed as argument 1, which is declared to never be null
/usr/include/string.h:65:33: note: nonnull attribute specified here
Found in #604

libwacom: only memcmp the led data if we have leds

---

data/isdv4-48b7.tablet

Add tablet of HP EliteBook x360 1040 G5
The file `isdv4-48b7.tablet` is a copy with small modifications of `isdv4-48c9.tablet` that is already in the database.

data: Add isdv-48b7

---

.github/workflows/check-for-sysinfo.yml
.github/workflows/freebsd.yml
.github/workflows/main.yml
.github/workflows/pages.yml

Jobs that use the GITHUB_TOKEN to perform sensitive actions on behalf of a real user may be granted a range of permissions. Instead of granting blanket permissions to read and write "all" APIs, we should really limit the permissions what any individual workflow or job can do.
This commit sets the default permissions for each workflow to "contents: read", which allows jobs to only read from the repository. The one job that requires additional permission is our "deploy" job which additionally requires write access.
Link: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idpermissions

github: Minimize permissions granted to automated workflows / jobs

---

.github/ISSUE_TEMPLATE/Bug_report.md
.github/ISSUE_TEMPLATE/New_device_support.md

Specifically make it a checkbox for users to click that they understand libwacom doesn't affect whether the device works. That should hopefully cut down on the issues filed wrongly, or at least it may tempt some users to read the wiki page and close the bug immediately again.

github: update the issue templates

---

data/dtc-121.tablet
data/dth-134.tablet

The model numbers for these devices likely should not include a hyphen.

data: Update ModelName for DTH134 and DTC121

---

.github/workflows/check-for-sysinfo.yml

The path provided by the tj-actions/changed-files is without the original path, so we need to prefix it with the directory we gave to that action.
Fixes the sysinfo error in #617

github: fix the sysinfo check workflow

---

data/wacom-hid-5362.tablet

Add laptop Lenovo Yoga 7 which uses Wacom HID 5362 Pen and Wacom HID 5362 Finger (vid: '0x056a', pid: '0x5362')

data: Add Wacom HID-5362

---

data/isdv4-5309.tablet

As discussed here: https://github.com/linuxwacom/wacom-hid-descriptors/issues/353

Add support for Lenovo ThinkPad X1 Yoga Gen 7

---

data/layouts/xp-pen-artist10s.svg
data/xp-pen-artist10s.tablet

I have som trouble with this descriptor, please help me with it.
- I had to use the string that is returned by `libinput list-devices` for kwin to recognize the descriptor. However, this is quite weird as the tablet is an XP-Pen Artist 10s, and it is not obvious what an UGEE device is. That would be nice to overwrite, yet the ModelName key has made no difference. Am I doing something wrong, or it is a problem with kwin/ksystem settings?
- In the example table file there is something about a system identifier generated by wacom-hid-descriptor. Howevert, that project seems to be about devices that are drawing computers, while this device is an external, usb connected drawing tablet. Is it alright that I omitted these comment lines or should I extend the .table file somehow?

add support for xp-pen artist 10s table

---

data/ingenic-6161.tablet

This is in reference to issue #602 . Adds support for the Ingenic touch/pen screens on the Lenovo Yoga Book 9i.
Edited 2Jan23 to correct laptop model name.

adding .tablet file for Ingenic touch and pen display.

---

data/libwacom.stylus

The Dell Active Pen is misconfigured in `libwacom.stylus`.
Firstly, The pen has 2 buttons.
Secondly "AES" pen does not properly illustrate what the pen is to the user.

Update Dell Active Pen

---

data/isdv4-50a0.tablet

Add tablet of Lenovo Yoga 370
The file isdv4-50a0.tablet is a copy with small modifications of isdv4-509d.tablet that is already in the database.

data: add isdv4-50a0

---

data/intuos-pro-2-l.tablet
data/intuos-pro-2-m.tablet
data/intuos-pro-2-s.tablet

The Windows driver at least blocks those but they work just fine. Add them here so we can look them up.
cc @jigpu, @Pinglinux, @Joshua-Dickens 
Note: this is required for [gnome-control-center!2244](https://gitlab.gnome.org/GNOME/gnome-control-center/-/merge_requests/2244) for the tablet to work with the old pens.

data: Intuos Pro 2 is compatible with Intuos 4 styli

---

data/elan-425a.tablet
data/elan-425b.tablet

Adding both touch panels for the new dualscreen Asus Zenbook Duo

data: add ELAN 9008 and 9009 (zenbook duo UX8406MA)

---

tools/list-local-devices.c

Example output appended now to the previous output:
```
devices:
- name: 'Wacom Intuos Pro M'
bus: 'usb'
vid: '0x056a'
pid: '0x0357'
nodes:
- /dev/input/event21: 'Wacom Intuos Pro M Finger'
- /dev/input/event18: 'Wacom Intuos Pro M Pen'
- /dev/input/event19: 'Wacom Intuos Pro M Pad'
styli:
- id: 0x842
name: 'Pro Pen 2'
type: 'general'
axes: ['x', 'y' , 'tilt', 'distance', 'pressure']
buttons: 2
erasers: [0x84a]
- id: 0x84a
name: 'Pro Pen 2 Eraser'
type: 'general'
axes: ['x', 'y' , 'tilt', 'distance', 'pressure']
buttons: 2
is_eraser: 'true'
eraser_type: 'invert'
...
```
and for the AES pens:
```
- id: 0x221
name: 'AES Pen'
type: 'mobile'
axes: ['x', 'y' , 'pressure']
buttons: 1
is_eraser: 'true'
eraser_type: 'button'
```

tools: list supported styli with the local tablet

---

data/generic.tablet

The vast majority of tablets these days are integrated into the respective system without a ring or strips, so let's update our generic tablet to match that.
This way an unknown tablet is more likely to match the tablet the user actually has.

Change the generic fallback tablet to be an integrated tablet

---

data/elan-2514.tablet

Sysinfo: https://github.com/linuxwacom/wacom-hid-descriptors/issues/362
HP ENVY x360 Convertible 15-ds1xxx just needed I2C ID in `elan-2514.tablet`

Add HP ENVY x360 Convertible 15-ds1xxx

---

data/elan-2bd6.tablet

The tablet works, but not sure about the stylus.
`tools/show-stylus.py` says it's only capable of generic stylus.
In Gnome settings I can see the stylus, but changing the button mappings doesn't do anything.
`libinput record` shows some event when pressing stylus buttons, but look random to me. When pressing buttons, sometimes I get a regular key press, sometimes nothing and sometimes eraser/rubber.  Also when using the stylus buttons, they every time produce different event.
Is there anything I can do about this?

Add lenovo IdeaPad Duet 3 10IGL5 (elan-2bd6)

---

.github/workflows/check-for-sysinfo.yml
.github/workflows/freebsd.yml
.github/workflows/label-commenter.yml
.github/workflows/main.yml
.github/workflows/pages.yml

From the current runs:
Node.js 16 actions are deprecated. Please update the following actions
to use Node.js 20: actions/checkout@v3, actions/setup-python@v4,
actions/upload-artifact@v3. For more information see:
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

ci: update to actions/checkout@v4

---

libwacom/libwacom.c

This path may be triggered if parent is NULL, calling g_object_unref on it will trigger a warning. This is unlikely to be triggered outside a custom test setup.

Don't unref a null device

---

data/wacom.example

Removes ambiguity regarding the purpose of ``NumStrips`` in the data/wacom.example file.

data: wacom.example: Document touch strips

---

libwacom/libwacom-database.c

g_key_file_get_string() returns the empty string where the key exists but isn't assigned to anything. Let's skip over that so we can have .tablet files with an empty Layout= line.
Fixes parts of #659

Skip over empty Layout= assignments

---

.github/workflows/main.yml
.github/workflows/pages.yml

These two trigger warnings:
> Node.js 16 actions are deprecated. Please update the following actions
> to use Node.js 20: actions/setup-python@v4, actions/upload-artifact@v3.
> For more information see:
> https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

github: update setup-python and upload-artifact actions

---

data/xp-pen-artist13-3-pro.tablet
data/xp-pen-deco-pro-mw.tablet
data/xp-pen-deco-pro-sw.tablet

They have a physical control that looks like a ring but it's not the Ring as our terminology has it. In the future we may add support for this as "Dial" but for now let's disable it.

data: XP pen tablets have no Rings

---

test/test-tablet-svg-validity.c

Previously we required a layout file for any tablet with pad buttons. This somewhat prevents us from adding tablet files for unknown tablets where we can get most of the information from external sources, e.g. see #659. As a result we're missing support for these tablets altogether when we could have at least partial support.
Let's drop this requirement in our tests, users who want their tablet working properly can submit layout files.
cc @JoseExposito

test: remove the requirement for a Layout file

---

meson.build
tools/debug-device.c

This one simply prints all return values for a device from our API, making it easier to figure out the exact behavior of a device. This is a debug utility so it is not installed.
Example output:
libwacom_get_name()                      -> "Wacom Cintiq 24HD touch"
libwacom_get_model_name()                -> "DTH-2400"
libwacom_get_layout_filename()           -> "data/layouts/cintiq-24hd.svg"
libwacom_get_vendor_id()                 -> 0x56a
libwacom_get_product_id()                -> 0xf8
libwacom_get_bustype()                   -> USB
libwacom_get_width()                     -> 21
libwacom_get_height()                    -> 13
libwacom_is_reversible()                 -> 0
--- 
cc @JoseExposito

tools: add a debug-device utility

---

data/layouts/movink.svg
data/libwacom.stylus
data/movink.tablet

Those commits are ready for Wacom Movink announced yesterday.

Add support for Wacom Movink 

---

data/wacom.example
libwacom/libwacom-database.c
libwacom/libwacom.c
libwacom/libwacom.h
libwacom/libwacom.sym
libwacom/libwacomint.h
test/test-load.c
test/test-tablet-svg-validity.c
test/test-tablet-validity.c
tools/debug-device.c

We already have a number of tablets with a relative dial that sends mouse wheel events (UCLOGIC/Huion/XP Pen devices, primarily) so let's add support for these in our description files.
This is copy/paste from the touch strip support.

Add support for relative dials

---

data/huion-kamvas-13.tablet

I am using the Kamvas 13 with the same model number, but it couldn't be detected by libwacom.
After some searching, I found out that the device name used in the descriptor doesn't match the one reported by my tablet.
I suspect there may be a different firmware installed.
Nevertheless, by adding the device names to the descriptor, everything is working.
Is it fine to use colon (:) as serperator?
The Pipe Symbol did not work on my distribution.
If not i can switch it to the other symbol.

Added more device names for kamvas 13 variants

---

test/test-tablet-svg-validity.c

It's a bit hard to figure out from the CI logs what failed because they may be truncated. And for users not intimitely familiar with the test suite it's not that simple either so let's put in a bunch of trace stataments that should at least point to where things go wrong.
cc @AesaraB

test: add some tracing to the svg validity test

---

test/test_data_files.py

This now useds the tablet file name as part of the test name as opposed to the less-useful "tabletfile123":
```
test/test_data_files.py::test_svg_exists[dtk-1651.tablet] PASSED                                                                                                                                                                                                                                                                                      [ 48%]```

test: add ids to the parametrized tablet file tests

---

libwacom/libwacom.c
libwacom/libwacom.h
libwacom/libwacom.sym
libwacom/libwacomint.h

This adds a new (and hopefully final) `libwacom_new_from...` call. This one takes a ~~match~~ `WacomBuilder` object which can now be constructed and filled by the user. In the future if we need to add further fields we can extend the `WacomBuilder` with a setter and have this function still work for us.
Notably, see https://github.com/linuxwacom/libwacom/pull/676#issuecomment-2092747045 the builder differentiates between the device name and the match name since those two may not be the same. The behaviour of the builder approach matches the existing approaches we have so the various `libwacom_new_from_` functions can be emulated with the new builder approach.
Prime motivation here is to be able to test better, I don't think any of our callers will switch since they all use …

Add libwacom_new_from_builder()

---

libwacom/libwacom-database.c
libwacom/libwacom.c
test/test_libwacom.py

First commit extracted from @JoseExposito's patchset in #659 but I think this needs a behaviour change to allow for uniq-only matches to take precedence over name matches, see https://github.com/linuxwacom/libwacom/pull/659#issuecomment-2091928456
Draft because it's untested and to test this we should add #677 and #676 first so we can test this properly.

Allow for a uniq-only match

---

libwacom/libwacom.c

Fixes: 61907bb80bc6 ("Add libwacom_new_from_builder to construct a new device (#676)")

Set the bustype in libwacom_new_for_path

---

data/wacom-hid-49a0-pen.tablet

Tested and working on my machine, a Dell latitude 5320 2-in-1, but I assume any device with a Wacom HID 49a0 would also work the same.
Sysinfo relating to this can be found here: https://github.com/linuxwacom/wacom-hid-descriptors/issues/378
I did make the file manually, so let me know if I missed something.

data: add Wacom HID 49A0 (Dell latitude 5320 2-in-1)

---

meson.build

This makes it easier to analyze log files

meson.build: make pytest more verbose

---

.github/workflows/main.yml
meson.build
test/conftest.py
test/test_udev_rules.py

Previously we'd create a uinput device for each of our tablets, then
query udev if the property is set. This takes a long time, in parts
thanks to the 300ms sleep to wait for the uinput device to be ready.
With now over 500 tablet files and most of those having multiple matches
we're looking at at minimum 500*0.3 seconds for a test run which isn't
really useful for a test like this.
Instead - let's query systemd-hwdb directly: construct a query string
our udev rule and query systemd-hwdb for the properties, then ensure we
have the ones we expect.
Closes #675
cc @alyssais

test: Replace the uinput-based hwdb test with a direct query

---

meson.build
test/conftest.py
test/test_libwacom.py

meson always sets `ASAN_OPTIONS` so the SVG tests didn't actually run in our CI. oops.
Filing as draft because pretty much all the SVGs added in #659 are missing some bits so they need to get fixed one-by-one.

Fix the pytest invocation

---

.github/workflows/main.yml

We want to drop our hwdb file into that directory, so let's make sure we can do that. Unlike gitlab, we're not running as root.
And by making `sytemd-hwdb` sticky, we can call it as user from our tests and voila, finally the hwdb tests are run in the CI too.

CI: create and make the hwdb.d directory writeable

---

data/layouts/xp-pen-deco-mini4.svg
data/xp-pen-deco-mini4.tablet

The layout is a copy of xp-pen-artist10s.svg.
HID-BPF drivers: https://gitlab.freedesktop.org/libevdev/udev-hid-bpf/-/merge_requests/88
Wacom HID descriptors: https://github.com/linuxwacom/wacom-hid-descriptors/issues/386

Add support for the XP-PEN Deco Mini 4

---

meson.build

Silences
../meson.build:307: WARNING: Project targets '>= 0.53.0' but uses feature
introduced in '0.56.0': meson.project_build_root.

meson.build: bump to meson 0.56.0

---

data/huion-wh1409.tablet
data/layouts/huion-wh1409.svg

Hello!
These are the two files (.tablet and .svg) to add support to the [Huion WH1409](https://www.huion.com/pen_tablet/Inspiroy/WH1409(8192).html). You can find the link to the sysinfo tarball within the .tablet file, or over [here](https://github.com/linuxwacom/wacom-hid-descriptors/issues/385).
Just for clarity, this is **not** the V2 version of the tablet.
I also need to state that while `libwacom-list-local-devices` shows the device correctly, KDE Tablet Settings, at least under X11, does not currently pick it up. Actually it picks the tablet up as a game controller, which is odd. I don't know if that bit of information is useful or not. Otherwise the tablet, including pen pressure, works just fine.
If you have any concerns about my pull request or anything regarding the last point, …

Add support for Huion WH1409

---

tools/libwacom-update-db.py

This should cut down on false positives or at least the ones caused by us.
Related https://github.com/DIGImend/digimend-kernel-drivers/pull/695, cc @JoseExposito

Don't mark Keyboard and Mouse devices as ID_INPUT_TABLET or ID_INPUT_TABLET_PAD

---

libwacom/libwacom.c

g_array_free() doesn't like NULL pointers so let's use g_clear_pointer which does the null checking for us. And this approach tends to be preferred these days anyway.

Use g_clear_pointer() during libwacom_*_unref()

---

libwacom/libwacom.c

This never stripped the quote off.
Fixes: 6026b34327a5 ("Fetch the name and uniq from udev properties, not sysfs (#708)")

Fix off-by-one check for stripping the quote from NAME/UNIQ

---

data/huion-inspiroy-2-s---h641p.tablet

This devices appears to have its own unique PID so we don't need the firmware match here. This matches the M and L version which also have a unique PID.
If Huion or Gaomon end up releasing devices that share this PID we'll have to re-instated the firmware match but for now let's drop it.
---
Slightly improves #718 since at least the udev properties are no longer needed

data: drop the firmware match from the Huion Inspiroy 2 S

---

libwacom/libwacom-database.c

leaked_storage: Variable "layout" going out of scope leaks the storage it points to.

Fix a memory leak

---

libwacom/libwacom.c
test/test_libwacom.py

If we end up using a fallback device, creating a default match triggers two complaints: an assert in bus_to_str() for the WBUSTYPE_UNKNOWN and one in libwacom_set_default_match() because the match we compose based on bustype/vid/pid does doesn't exist in the list of the generic device's matches.
Closes #721, #722

Don't create a default match for fallback devices

---

libwacom/libwacom.c
test/__init__.py
test/test_libwacom.py

Regression as a result of the switch to use the builder

Set the device name for a fallback device

---

data/libwacom.stylus
data/wacom-movink.tablet

We found that there was the unnecessary ID remained on libwacom.stylus
and Movink supports more groups for libwacom to work properly.

Id and group modifications

---

data/layouts/wacom-movink-13.svg
data/libwacom.stylus
data/wacom-movink-13.tablet

Previously uploaded files for Wacom Movink 13 had slightly a wrong name, which was "Wacom Movink".
Therefore, the names such as "movink" and "Movink" were corrected to "movink-13" and "Movink 13" reflecting more appropriate product name.
The commits involved with deletions, so please let me know if there's something wrong.

Movink naming modification

---

data/libwacom.stylus
data/wacom-cintiq-pro-17.tablet
data/wacom-cintiq-pro-22.tablet
data/wacom-cintiq-pro-27.tablet
data/wacom-movink-13.tablet

The Pro Pen 3E is a version of the Pro Pen 3 which includes an eraser and is compatible with the same devices. This patch also adds the propen3 group to Movink, which should have had it.

data: Add stylus definition for Pro Pen 3E

---

data/wacom-intuos-pro-2-l.tablet
data/wacom-intuos-pro-2-m.tablet
data/wacom-intuos-pro-2-s.tablet
data/wacom-intuos-pro-l.tablet
data/wacom-intuos-pro-m.tablet
data/wacom-intuos-pro-s.tablet

Updates the comment headers for these devices to use the marketing name (already properly set in the "Name" field) and move the generation information to its own separate line).

data: Update comment header for 1st- and 2nd-gen Intuos Pro

---

.github/workflows/main.yml
meson.build
run-full-test.sh

This may or may not fix the issues with timeouts on the hwdb query tests, see #694.
On top of that skip all pytest for valgrind because there's no point.

meson.build: bump the timeout for pytest to 60s and skip valgrinding python tests

---

libwacom/libwacom-database.c
libwacom/libwacom.c
run-full-test.sh
test/test-stylus-validity.c
tools/list-local-devices.c

Prep work for other patches, might as well get those out

A number of cleanup patches

---

.github/workflows/main.yml

Some of of our tests dump temporary hwdbs there, let's make this writable (it's already done for the non-valgrind job).
Closes #701

ci: make /etc/udev/hwdb.d writable in the valgrind job too

---

meson.build

Fixes: 9c9e234f4ae3 ("man: add a man page for libwacom-show-stylus")

meson.build: install the libwacom-show-stylus man page

---

data/isdv4-52c2.tablet

I don't think this is complete yet, but since just creating issues is discouraged, I thought I'd get started and then finish the PR according to the changes requests. This is trying to add support for the Wacom HID 52C2 in the Lenovo Yoga 9 14IAP7. I don't think `sysinfo.sh` succeeded in creating a .tablet file (at least I couldn't find one), so I tried adapting a similar one, and it seems to at least get recognized by `libwacom-list-local-devices` now. But I wasn't sure about all values and how to adapt them, I tried following the "Adding a new device" guide.
One thing I'm not sure how to handle is this device shows a "Finger" and "Pen" device, are these supposed to go in the same file or is the "Finger" device not meant to be in this repo any way? Also, the initial reason why I stumbled …

Add support for Lenovo Yoga 9 14IAP7

---

data/libwacom.stylus
libwacom/libwacom-database.c
libwacom/libwacom.c
libwacom/libwacom.h
libwacom/libwacom.sym
libwacom/libwacomint.h
test/__init__.py
test/test-dbverify.c
test/test-stylus-validity.c
test/test-tablet-validity.c
test/test_libwacom.py
tools/debug-device.c
tools/list-compatible-styli.c
tools/list-local-devices.c

This adds support for styli that aren't implicitly wacom styli.
Right now our API supports two types of styli: the few generic ones with IDs that wacom doesn't (hopefully won't ever) use. And all other real styli with actual ids but those are assumed to be Wacom styli - if any other vendor starts using IDs (possibly the one in #636 but it's not fully clear whether it is a true stylus id) we are running into issues because we won't be able to differentiate.
This patch adds a vendor id to the `WacomStylus` and the associated APIs. The generic pens have a vendor id of 0, everything else defaults to 0x56a unless explicitly specified otherwise.
The current set of APIs is deprecated and replaced with an API that returns a `WacomStylus` instead of just an id, e.g. `const int * …

Add support for styli from vendors other than Wacom

---

data/wacom-isdv4-52c2.tablet

This is a follow-up to my previous PR, which just removes some old properties that still are present in the [wiki](https://github.com/linuxwacom/libwacom/wiki/Tablet-Definition-Files) but not needed any more according to the example file. I also renamed the file to fit with other similar devices and removed the Pen suffix for the Name property since both devices are handled with the same tablet definition.
Last but not least I added the Styli property, not sure if that changes anything, but it should be correct according to all the other Lenovo tablet definitions.

Minor adjustments for Lenovo Yoga 9 14IAP7

---

README.md

These instructions are old, and then I followed them because I didn't know there was a wiki page. Let's link that in the README so other people don't make my mistake.

Point people to the better fleshed out wiki page for adding new devices

---

.github/workflows/main.yml
tools/clean_svg.py

Fixes the crasher reported by @Deevad in https://github.com/linuxwacom/libwacom/pull/777#issuecomment-2405806463

Fix error in clean_svg.py and allow it to run on `.tablet` files

---

README.md

These are now maintained alongside the rest of the building instructions on the wiki. The text for the current version of libwacom is kept.
Closes #785

Remove testing instructions from the README

---

data/layouts/xp-pen-artist22r-pro.svg
data/xp-pen-artist-22r-pro.tablet

This adds support for the 22R Pro, a tablet with many too many controls on it :) This passes `test-tablet-validity` and `list-local-devices`.
```
devices:
- name: 'XP-Pen Artist 22R Pro'
bus: 'usb'
vid: '0x28bd'
pid: '0x091b'
nodes: 
- /dev/input/event4: 'UGTABLET 21.5 inch PenDisplay Pen'
styli:
- id: 0xffffd
name: 'General Pen with no Eraser'
type: 'general'
axes: ['x', 'y' , 'pressure']
buttons: 2
erasers: []
- name: 'XP-Pen Artist 22R Pro'
bus: 'usb'
vid: '0x28bd'
pid: '0x091b'
nodes: 
- /dev/input/event7: 'UGTABLET 21.5 inch PenDisplay Pad'
styli:
- id: 0xffffd
name: 'General Pen with no Eraser'
type: 'general'
axes: ['x', 'y' , 'pressure']
buttons: 2
erasers: []
```

data: Add support for the XP-Pen Artist 22R Pro

---

data/elan-2513.tablet

Referring to [this sysinfo](https://github.com/linuxwacom/wacom-hid-descriptors/issues/419)

Added support for ELAN-2514 variant 04f3:2f9d (HP Envy x360 15-ew0xxx)

---

tools/show-stylus.py

This only fixes the stylus id part of it, VIDs are still unhandled.
Fixes: 884d4230d1b7 ("Support styli from vendors other than Wacom")
---
Found while handling https://github.com/linuxwacom/libwacom/pull/795

tools: fix show-stylus to handle vendor styli

---

data/wacom.stylus

I'm not sure if `BAT_HID` is required. Also as I have understood the lenovo digital pen 2 has tilt "detection", but not tilt "recognition", which I believe means it knows when it's tilted but not how much so I didn't put `Tilt` in the `Axes=` field, but I'm not 100% sure

Update wacom.stylus - added Lenovo Digital Pen 2

---

data/wacom-ek-remote.tablet
libwacom/libwacom-database.c
libwacom/libwacom.c
libwacom/libwacom.h

In commit 2dd3501fd3dd ("Deprecate the WacomClass in the API") libwacom_get_class() was deprecated. But that function remains the only way to reliably identify the ExpressKey Remote as remote. This didn't really matter since at least GNOME identifies that by PID/VID rather than class.
Other vendors now make their own remotes (XP Pen ACK05, Huion Keypad mini) so let's add an integration flag for those.
Related #777

Add a new IntegratedIn=Remote flag

---

tools/clean_svg.py

Taken from #788 so we can keep the device support separate from these fixes here
cc @bentiss

Fixes to clean-svg.py

---

libwacom/libwacom-database.c
libwacom/libwacom.h

Useful for testing e.g. #788 with built-in tools like `debug-device`. The new file is in `/etc/libwacom` to make it system-wide accessible but `debug-device` only uses the git datadir by default.
This MR allows for:
```
./build/debug-device --database /etc/libwacom:$PWD/data /dev/input/event19
```
and other testing of databases distributed across multiple data dirs.

Allow for datadirs to be colon-separated

---

data/wacom-isdv4-5214.tablet

Hi everyone,
My Flex 5 seems to have an id that's not in the database.
The sysinfo script didn't generate a tablet file so I edited it from wacom-isdv4-5215.tablet.
It seems to work fine on my unit in Ubuntu 24.10 and it passed the meson test.
[testlog.txt](https://github.com/user-attachments/files/17535127/testlog.txt)

Add Support for Wacom HID 5214 (Lenovo IdeaPad Flex 5 14ARE05 rev.81X2)

---

data/wacom-isdv4-5229.tablet

Hello everyone,
i have a Lenovo Yoga X1 Gen5, which has a display with integrated privacy function - think that might be the reason I have a different device id.
the way i implemented it makes it working correctly with the meson test, but creates following warning:
```
❯ libwacom-list-local-devices
failed to match 'usb|056a|5229' for product/vendor IDs. Skipping.
'usb|056a|5229' is an invalid DeviceMatch in '/usr/share/libwacom/wacom-isdv4-5229.tablet'
failed to match 'usb|056a|522a' for product/vendor IDs. Skipping.
'usb|056a|522a' is an invalid DeviceMatch in '/usr/share/libwacom/wacom-isdv4-5229.tablet'
failed to match 'usb|056a|522b' for product/vendor IDs. Skipping.
'usb|056a|522b' is an invalid DeviceMatch in '/usr/share/libwacom/wacom-isdv4-5229.tablet' …
```

extended Lenovo Yoga X1 Gen5 Support

---

data/elan-2514.tablet

Referring to this [sysinfo](https://github.com/linuxwacom/wacom-hid-descriptors/issues/414)

Add Support for the ELAN-2514 04F3:29DF (HP Spectre x360 13-aw0020ng)

---

data/layouts/xp-pen-ack05-remote.svg
data/xp-pen-ack05-remote.tablet

Taking over #777, because I have the HW locally and could do some more testing.
This has a couple of `clean_svg.py` fixes, and the SVG from @Deevad (fixed by me).
The dial still doesn't work properly in the overlay, so I wonder if the problem is not in gnome-settings-daemon. KDE only shows the buttons, not the dial.
I also tried adding the "modes", but it seems that they are not recognized by default by g-s-d (is this because there is no LEDs on the device and then non sysfs for them?)
Also, still no sysinfo, this is pretty much pre-development at thios stage, and we need to figure out if we are happy with the button mapping first.

data: add the XP-Pen ACK05 Remote, take 2

---

.github/workflows/main.yml
libwacom/libwacom-database.c
test/test_libwacom.py
tools/libwacom-update-db.py
tools/show-stylus.py

This completes the traditional triplet of $XDG_CONFIG_HOME, /etc, and
/usr/share for configuration files.
Having custom .tablet files in $XDG_CONFIG_HOME makes it easier for
immutable systems and also for backups that only back up the user home
directory.

Support $XDG_CONFIG_HOME/libwacom as additional path

---

libwacom/libwacom.c
libwacom/libwacomint.h
test/__init__.py
test/test_libwacom.py

The three generic pens have a vendor-id of 0 so let's special case those for the now-deprecated API.

Special-case the generic pens for libwacom_get_supported_styli

---

test/test_data_files.py

The clean_svg.py script has a problem with those, see #818, but either way there's little to be gained from them anyway.

test: do not allow empty Layout= lines

---

tools/list-local-devices.c

This makes the output slightly more useful since we can see what the device should be matched without a separate udevadm info query.

tools/list-local-devices: print the vid/pid if available

---

libwacom/libwacom-database.c
test/test-tablet-validity.c
tools/list-local-devices.c

If a device explicitly lists Stylus=false don't force it to the generic styli.

Don't set up styli for devices without a stylus

---

test/test_svg.py

Fixes "AttributeError: 'NoneType' object has no attribute 'split'"

test/test_svg: don't fail if we don't have any classes on an element

---

data/huion-keydial-k20.tablet
data/layouts/huion-keydial-k20.svg
test/test_svg.py

This is the successor to the KD100 and optically the same so these files are copy/paste from the KD100
@deevad has a nicer-looking svg in [udev-hid-bpf#35](https://gitlab.freedesktop.org/libevdev/udev-hid-bpf/-/issues/35) but unfortunately that one requires a lot of manual fixes for the various CSS classes and object IDs we require. In the interest of getting this done quickly, here's a copy/pasted one that's been modified quickly.
This is a draft because I haven't yet been able to convince gnome settings to show the OSD

data: add Huion KeyDial K20

---

.github/workflows/main.yml
libwacom/libwacom-database.c

Commit 2dc213c30e27 introduced a duplicate resolution to fix #379 so that we could have a tablet file in /etc/libwacom that had a DeviceMatch that partially overlapped with a DeviceMatch in /usr/share/libwacom, e.g. in this setup:
DeviceMatch=usb|1234|abcd;bluetooth|1234|abcd
DeviceMatch=usb|1234|abcd
This triggered a bug: during the duplicate resolution the device match was removed from the currently parsed file, leading to the file having no device matches which triggered a g_warn_if_reached().
This approach is too complicated and likely unnecessary, use a more conventional approach where a named file hide the same file in any other datadir, i.e. /etc/libwacom/foo-bar.tablet will hide /usr/share/libwacom/foo-bar.tablet, the latter of which will not be parsed at all.
This corresponds to …

Assume .tablet files shadow any ones with the same name

---

data/lenovo.stylus

Please add the Lenovo Slim Pen to the database.
It is shipped with the Laptop [Lenovo ThinkPad X1 2-in-1 Gen 9](https://github.com/linuxwacom/wacom-hid-descriptors/tree/master/Lenovo%20ThinkPad%20X1%202-in-1%20Gen%209).
After adding the configuration, I was able to configure the pen using the Gnome Control Center.
I'm not sure whether it is supposed to, but the pen does not appear in the Power section.

Add Lenovo Slim Pen

---

.github/ISSUE_TEMPLATE/Bug_report.md
.github/ISSUE_TEMPLATE/New_device_support.md

libwacom does *not* affect the device. Oopsie.
As seen in e.g. #850

Fix the issue templates

---

libwacom/libwacom.c
test/test_libwacom.py

libwacom_new_for_path() is invoked on an actual device and those sometimes have a bustype of zero - especially where they're created as virtual device.
Since those devices exist we should handle them correctly even though the only thing we will reliably do here is provide the fallback device (if requested).
Closes #840

Allow for a bustype of 0 on real devices

---

libwacom/libwacom-database.c
libwacom/libwacom.c
libwacom/libwacom.h
libwacom/libwacom.sym
libwacom/libwacomint.h
test/__init__.py
test/test_libwacom.py
tools/debug-device.c

Add libwacom_get_button_modeswitch_mode() to return the target mode for a given button. On the vast majority of devices this will be "next" but the Wacom Mobile Studio and the Cintiq 24HD have multiple mode switch buttons that correspond to the respective mode (i.e. button N should switch to mode M).
This is already effectively encoded in our tablet database so we can simply use the order of buttons in that file to assign the modes.
Closes #854

Add support for getting the target mode for a modeswitch button

---

.github/workflows/main.yml

As per #859
Peter wanted to see if the CI fails after excising some code.
However, I am not very familiar with GitHub CI, so I can't say whether the CI will use the clang compiler (for which the workaround was provisioned).

github: Remove redundant meson build option

---

tools/debug-device.c

Since all we do is print libwacom's output there is no need for this
tool to require an event node. A simple DeviceMatch is sufficient to
look up whatever device we want to debug.
This now allows for things like `./buidldir/debug-device "usb|056a|00f4"` and get the output of libwacom's API for that device.

Support DeviceMatch in debug-device

---

data/xp-pen-deco01-v3.tablet

Basically the same as the v2, at least as seen by libwacom (bar name and pid).
cc @Deevad - can you submit the sysinfo to [wacom-hid-descriptors](https://github.com/linuxwacom/wacom-hid-descriptors) please, this requires the physical so I can't do those with the hid-recordings from https://gitlab.freedesktop.org/libevdev/udev-hid-bpf/-/issues/54

Add the XP Pen Deco01 v3

---

data/wacom.stylus
libwacom/libwacom-database.c
libwacom/libwacom.h
test/test_libwacom.py

Add a new keyword to libwacom.stylus so we can share the settings among those tools that of the same type.
This supersedes #844 and has the various missing bits:
- style changes and memleak fixes
- better error path handling through `g_set_error()`
- support for full stylus ids (`vid:pid` format)
- test case added so we can make sure the overrides actually works
Closes #761
Closes #884

Support "AliasOf" keyword 

---

data/xp-pen-deco-pro-s.tablet

Pull request adds support for XP-Pen Deco Pro S tablet. This model is virtually identical to the XP-Pen Deco Pro SW tablet, just without the Bluetooth connectivity.

Support for XP-Pen Deco Pro S

---

meson.build
tools/list-compatible-styli.c

Doesn't really test for anything specific other than the tool not crashing. That may just catch the odd error here or there.

test: add invocations of the tools to our test suite

---

.clang-tidy
.github/workflows/main.yml
libwacom/libwacom-database.c
libwacom/libwacom.c
libwacom/libwacomint.h
run-full-test.sh
test/test-dbverify.c
test/test-stylus-validity.c
test/test-tablet-validity.c
tools/debug-device.c
tools/list-compatible-styli.c
tools/list-devices.c
tools/list-local-devices.c

Closes #142 
`scan-build` prevented us from using these in the past since it would throw false positives for memleaks everywhere. We can instead run `clang-tidy` though which provides configuration[^1] via `.clang-tidy` where we can just disable that warning.
I've used the equivalent of `g_auto` in other projects and it makes code so much nicer that it's a huge win, even where there aren't lots of allocations.
Unfortunately that warning also disables double-free and use-after-free warnings but with consistent use of `g_auto` we should never have those anyway since we will never call free ourselves outside of dedicated cleanup functions. So I think that's a fair trade off.
side-note: `.clang-tidy` would also eventually allow us to enforce consistent coding style, see e.g. #868.
This patch …

Use g_autofree/g_autoptr and friends for automatic memory management 

---

data/framework-laptop12.tablet

To validate:
```
> sudo cp data/framework-laptop12.tablet /usr/share/libwacom/
> sudo libwacom-list-local-devices
devices:
- name: 'Framework Laptop 12'
bus: 'i2c'
vid: 0x222a
pid: 0x5539
nodes:
- /dev/input/event9: 'ILIT2901:00 222A:5539 Stylus'
styli:
- id: 0xffffd
vid: 0x0000
name: 'General Pen with no Eraser'
type: 'general'
axes: ['x', 'y' , 'pressure']
buttons: 2
erasers: []
```

Initial config for Framework 12 touchscreen

---

libwacom/libwacom.c

Programs using libwacom on a system without any supported device are being subject to a segfault:
malloc_consolidate(): unaligned fastbin chunk detected
Abandon (core dumped)
Using valgrind on list-local-devices shows the issue:
==29751== Command: ./list-local-devices
==29751==
==29751== Invalid free() / delete / delete[] / realloc()
==29751==    at 0x4842E43: free (vg_replace_malloc.c:989)
==29751==    by 0x48D8D44: g_free (gmem.c:208)
==29751==    by 0x485BD8B: g_autoptr_cleanup_generic_gfree (glib-autocleanups.h:32)
==29751==    by 0x485DCC2: libwacom_new_from_path (libwacom.c:790)
==29751==    by 0x4014B0: main (list-local-devices.c:301)
==29751==  Address 0x5234aa0 is 0 bytes inside a block of size 28 free'd
==29751==    at 0x4842E43: free (vg_replace_malloc.c:989)
==29751==    by …

get_device_info(): don't leak free()'ed pointer on error

---

tools/list-local-devices.c

The regression was caused by ac375537f2592307f6056dbd01f8321eef8af1f6.
The command appears do what it needs to do, it simply segfaults after everything was executed.

Fix segfault after running list-local-devices

---

meson.build

Fixes:
WARNING: Project specifies a minimum meson_version '>= 0.57.0'
but uses features which were added in newer versions:

meson.build: bump minimum version for format strings

---

data/huion-keydial-k20.tablet

Like the USB version this one does not work out of the box, it requires report descriptor mangling. See this issue for details https://gitlab.freedesktop.org/libevdev/udev-hid-bpf/

data: add the Huion KeyDial K20 over bluetooth

---

data/huion-kamvas-pro-13.tablet

Later Huion Kamvas Pro 13 (GT-133) models have the productId 006d (of course) so I added the uniq identifier to the .tablet file. Tested working on my local system.
A word of note: For some reason `udevadm info` (v258) did not show a UNIQ attribtue, but `udevadm info -a` returned `ATTRS{uniq}=="HUION_M182_190116"`
The wiki might need to be updated to reflect this, not sure which version caused the change.

Added uniq identifier to Huion Kamvas Pro 13 (GT-133)
